package mailchimp

import (
	"encoding/json"
	"sort"
	"testing"
	"time"

	"github.com/trufflesecurity/trufflehog/v3/pkg/analyzer/analyzers"
	"github.com/trufflesecurity/trufflehog/v3/pkg/analyzer/config"
	"github.com/trufflesecurity/trufflehog/v3/pkg/common"
	"github.com/trufflesecurity/trufflehog/v3/pkg/context"
)

func TestAnalyzer_Analyze(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()
	testSecrets, err := common.GetSecret(ctx, "trufflehog-testing", "detectors2")
	if err != nil {
		t.Fatalf("could not get test secrets from GCP: %s", err)
	}

	tests := []struct {
		name    string
		key     string
		want    string // JSON string
		wantErr bool
	}{
		{
			name: "valid Mailchimp key",
			key:  testSecrets.MustGetField("MAILCHIMP"),
			want: `{
				"AnalyzerType":7,
				"Bindings":[
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"pause_unpublish_emails",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"view_abuse_reports",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"email_contact_details",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"view_customer_journey",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"leave_comments",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"send_messages",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"check_reconnect_integrations",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"audience_import",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"edit_survey",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"edit_audience_settings",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"create_survey",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"archive_contacts",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"edit_emails",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"verify_a_domain",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"publish_form",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"invite_users",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"change_company_organization_name",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"domain_performance",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"publish_unpublish_your_website",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"toggle_user_notifications",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"edit_templates",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"use_conversations",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"top_locations",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"change_billing_information",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"referral_program",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"connect_a_domain",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"add_files_to_content_studio",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"create_your_website",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"e_commerce_product_activity",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"create_a_landing_page",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"turn_on_pause_turn_back_on",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"send_publish_emails",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"delete_emails",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"delete_contacts",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"email_open_details",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"revoke_account_access",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"add_contacts",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"account_export",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"audience_export",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"create_or_import_templates",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"create_send_sms_mms_messages",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"replicate_a_landing_page",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"publish_survey",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"set_user_access_level",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"add_or_access_api_keys",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"edit_form",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"purchase_sms_credits",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"view_sms_reports",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"submit_sms_marketing_application",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"close_account",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"view_audiences",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"view_messages",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"delete_survey",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"require_2_factor_authentication",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"view_report",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"view_email_statistics",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"create_form",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"view_email_reports",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"publish_unpublish_a_landing_page",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"create_audiences",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"create_emails",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"edit_customer_journey",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"view_segments",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"create_customer_journey",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"delete_form",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"opt_in_to_receive_emails_from_mailchimp",
						 "Parent":null
					  }
				   },
				   {
					  "Resource":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  },
					  "Permission":{
						 "Value":"view_email_recipients",
						 "Parent":null
					  }
				   }
				],
				"UnboundedResources":[
				   {
					  "Name":"trufflesec.com",
					  "FullyQualifiedName":"mailchimp.com/domain/trufflesec.com",
					  "Type":"domain",
					  "Metadata":{
						 "authenticated":false,
						 "verified":true
					  },
					  "Parent":{
						 "Name":"TruffleHog",
						 "FullyQualifiedName":"mailchimp.com/account/09f02f6ec9b78ff5c3ce52f96",
						 "Type":"account",
						 "Metadata":{
							"account_timezone":"America/New_York",
							"address1":"333 Twin Dolphin Dr Ste 230",
							"address2":"",
							"city":"Redwood City",
							"company":"TruffleHog",
							"country":"US",
							"email":"detectors@trufflesec.com",
							"first_name":"Truffle",
							"last_login":"2024-08-16T10:39:15+00:00",
							"last_name":"Security",
							"member_since":"2024-08-16T10:37:37+00:00",
							"pricing_plan":"forever_free",
							"role":"owner",
							"state":"CA",
							"total_subscribers":1,
							"zip":"94065-1416"
						 },
						 "Parent":null
					  }
				   }
				],
				"Metadata":null
			 }`,
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			a := Analyzer{Cfg: &config.Config{}}
			got, err := a.Analyze(ctx, map[string]string{"key": tt.key})
			if (err != nil) != tt.wantErr {
				t.Errorf("Analyzer.Analyze() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			// Bindings need to be in the same order to be comparable
			sortBindings(got.Bindings)

			// Marshal the actual result to JSON
			gotJSON, err := json.Marshal(got)
			if err != nil {
				t.Fatalf("could not marshal got to JSON: %s", err)
			}

			// Parse the expected JSON string
			var wantObj analyzers.AnalyzerResult
			if err := json.Unmarshal([]byte(tt.want), &wantObj); err != nil {
				t.Fatalf("could not unmarshal want JSON string: %s", err)
			}

			// Bindings need to be in the same order to be comparable
			sortBindings(wantObj.Bindings)

			// Marshal the expected result to JSON (to normalize)
			wantJSON, err := json.Marshal(wantObj)
			if err != nil {
				t.Fatalf("could not marshal want to JSON: %s", err)
			}

			// Compare the JSON strings
			if string(gotJSON) != string(wantJSON) {
				// Pretty-print both JSON strings for easier comparison
				var gotIndented, wantIndented []byte
				gotIndented, err = json.MarshalIndent(got, "", " ")
				if err != nil {
					t.Fatalf("could not marshal got to indented JSON: %s", err)
				}
				wantIndented, err = json.MarshalIndent(wantObj, "", " ")
				if err != nil {
					t.Fatalf("could not marshal want to indented JSON: %s", err)
				}
				t.Errorf("Analyzer.Analyze() = %s, want %s", gotIndented, wantIndented)
			}
		})
	}
}

// Helper function to sort bindings
func sortBindings(bindings []analyzers.Binding) {
	sort.SliceStable(bindings, func(i, j int) bool {
		if bindings[i].Resource.Name == bindings[j].Resource.Name {
			return bindings[i].Permission.Value < bindings[j].Permission.Value
		}
		return bindings[i].Resource.Name < bindings[j].Resource.Name
	})
}
