FROM alpine:3.20

RUN apk add --no-cache bash git openssh-client ca-certificates rpm2cpio binutils cpio \
    && rm -rf /var/cache/apk/* && update-ca-certificates
WORKDIR /usr/bin/
COPY trufflehog .
COPY entrypoint.sh /etc/entrypoint.sh
RUN chmod +x /etc/entrypoint.sh
ENTRYPOINT ["/etc/entrypoint.sh"]
