package engine

import (
	"github.com/trufflesecurity/trufflehog/pkg/detectors"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/abbysale"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/abuseipdb"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/accuweather"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/adafruitio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/adobeio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/adzuna"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/agora"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/airbrakeprojectkey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/airbrakeuserkey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/airship"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/airtableapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/airvisual"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/alconost"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/alegra"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/aletheiaapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/algoliaadminkey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/alibaba"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/alienvault"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/allsports"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/amadeus"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ambee"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/amplitudeapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/anypoint"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/api2cart"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/apideck"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/apiflash"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/apifonica"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/apify"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/apollo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/appcues"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/appfollow"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/apptivo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/artsy"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/asanaoauth"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/asanapersonalaccesstoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/assemblyai"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/audd"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/auth0managementapitoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/autodesk"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/autoklose"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/autopilot"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/aviationstack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/aws"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/axonaut"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/aylien"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ayrshare"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/azure"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/bannerbear"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/baremetrics"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/baseapiio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/beamer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/besttime"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/billomat"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/bitbar"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/bitcoinaverage"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/bitfinex"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/bitlyaccesstoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/bitmex"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/blablabus"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/blazemeter"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/blitapp"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/blogger"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/bombbomb"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/brandfetch"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/browshot"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/bugherd"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/bugsnag"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/buildkite"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/bulbul"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/buttercms"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/calendarific"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/calendlyapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/calorieninja"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/campayn"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/cannyio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/capsulecrm"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/carboninterface"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/censys"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/centralstationcrm"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/chatbot"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/checkout"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/cicero"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/circleci"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/clarifai"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/clearbit"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/clickhelp"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/clicksendsms"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/clickuppersonaltoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/clinchpad"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/clockify"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/clockworksms"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/closecrm"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/cloudflareapitoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/cloudflarecakey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/cloudmersive"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/cloudplan"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/cloverly"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/clustdoc"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/codacy"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/coinapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/coinbase"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/coinlayer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/coinlib"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/commercejs"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/commodities"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/companyhub"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/confluent"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/contentfulpersonalaccesstoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/convertkit"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/copper"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/countrylayer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/coveralls"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/crowdin"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/cryptocompare"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/currencycloud"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/currencyfreaks"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/currencylayer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/currencyscoop"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/currentsapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/customerguru"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/customerio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/d7network"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/dailyco"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/dandelion"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/datadogtoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/datafire"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/datagov"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/deepai"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/deepgram"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/delighted"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/detectlanguage"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/dfuse"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/digitaloceantoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/discordbottoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/discordwebhook"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/dnscheck"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/documo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/doppler"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/dotmailer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/dovico"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/droneci"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/dropbox"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/dwolla"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/dynalist"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/dyspatch"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/easyinsight"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/edamam"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/edenai"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/elasticemail"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/enigma"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ethplorer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/etsyapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/everhour"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/exchangerateapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/exchangeratesapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/facebookoauth"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/faceplusplus"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/fakejson"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/fastlypersonaltoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/feedier"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/fetchrss"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/figmapersonalaccesstoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/fileio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/finage"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/financialmodelingprep"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/finnhub"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/fixerio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/flatio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/fleetbase"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/flickr"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/flightapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/float"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/flowflu"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/flutterwave"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/foursquare"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/frameio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/front"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/fulcrum"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/fullstory"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/fxmarket"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/gcp"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/gengo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/geoapify"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/geocode"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/geocodify"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/geocodio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/geoipifi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/getemail"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/getemails"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/getgeoapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/getgist"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/github"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/github_old"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/githubapp"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/gitlab"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/gitlabv2"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/gitter"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/glassnode"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/gocardless"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/graphcms"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/graphhopper"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/groovehq"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/guardianapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/gyazo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/happyscribe"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/harvest"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/hellosign"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/helpcrunch"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/helpscout"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/hereapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/heroku"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/hive"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/hiveage"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/holidayapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/host"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/html2pdf"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/hubspotapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/humanity"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/hunter"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/hypertrack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/iconfinder"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/iexcloud"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/imagekit"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/imagga"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/impala"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/insightly"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/integromat"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/intercom"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/intrinio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ipapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ipgeolocation"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ipify"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ipinfodb"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ipquality"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ipstack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/jdbc"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/jiratoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/jotform"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/jumpcloud"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/juro"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/karmacrm"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/keenio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/kickbox"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/kontent"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/kraken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/kylas"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/languagelayer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/lastfm"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/launchdarkly"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/leadfeeder"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/lessannoyingcrm"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/lexigram"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/linearapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/linenotify"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/linkpreview"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/liveagent"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/locationiq"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/loginradius"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/lokalisetoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/loyverse"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/m3o"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/macaddress"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/magnetic"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mailboxlayer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mailchimp"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mailerlite"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mailgun"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mailjetbasicauth"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mailjetsms"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mailmodo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mailsac"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mandrill"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mapbox"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mapquest"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/marketstack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mattermostpersonaltoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mavenlink"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/maxmindlicense"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/meaningcloud"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mediastack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mesibo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/messagebird"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/metrilo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/microsoftteamswebhook"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/mixpanel"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/monday"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/moosend"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/myfreshworks"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/nasdaqdatalink"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/nethunt"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/netlify"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/neutrinoapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/newrelicpersonalapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/newsapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/newscatcher"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/nexmoapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/nftport"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/nicereply"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/nimble"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/nitro"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/noticeable"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/notion"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/numverify"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/nutritionix"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/nylas"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/nytimes"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/okta"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/omnisend"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/onedesk"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/onelogin"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/onepagecrm"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/onwaterio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/oopspam"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/opencagedata"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/opengraphr"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/openuv"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/openweather"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/optimizely"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/owlbot"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pagerdutyapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pandadoc"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/paralleldots"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/partnerstack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/passbase"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pastebin"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/paymongo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/paypaloauth"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/paystack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pdflayer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pdfshift"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pepipost"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pipedrive"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pivotaltracker"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pixabay"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/planyo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/plivo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/poloniex"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/polygon"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/positionstack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/postageapp"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/posthog"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/postman"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/postmark"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/powrbot"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/privatekey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/prospectcrm"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/prospectio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/protocolsio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/proxycrawl"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pubnubpublishkey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pubnubsubscriptionkey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/purestake"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pushbulletapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/pusherchannelkey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/qualaroo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/qubole"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/quickmetrics"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/rapidapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/rawg"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/razorpay"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/readme"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/reallysimplesystems"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/rebrandly"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/refiner"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/restpack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/restpackhtmltopdfapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/restpackscreenshotapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/revampcrm"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ringcentral"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ritekit"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/roaring"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/rocketreach"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/roninapp"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/route4me"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/rubygems"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/runrunit"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/salesblink"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/salescookie"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/salesflare"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/satismeterprojectkey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/satismeterwritekey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/saucelabs"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/scalewaykey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/scrapeowl"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/scraperapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/scraperbox"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/scrapestack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/scrapingant"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/scrapingbee"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/screenshotapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/screenshotlayer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/securitytrails"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/segmentapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/semaphore"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/sendgrid"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/sendinbluev2"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/sentiment"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/sentrytoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/serphouse"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/serpstack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/sheety"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/shipday"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/shodankey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/shortcut"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/shutterstock"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/shutterstockoauth"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/signalwire"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/signaturit"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/signupgenius"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/simplesat"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/simvoly"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/sinchmessage"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/siteleaf"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/skrappio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/skybiometry"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/slack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/slackwebhook"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/smartsheets"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/smartystreets"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/smooch"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/snipcart"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/snykkey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/sparkpost"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/splunkobservabilitytoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/spoonacular"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/sportsmonk"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/spotifykey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/square"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/squareapp"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/squarespace"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/squareup"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/sslmate"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/stitchdata"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/stockdata"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/storecove"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/stormglass"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/storyblok"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/storychief"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/strava"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/streak"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/stripe"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/stytch"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/sumologickey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/surveyanyplace"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/surveybot"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/surveysparrow"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/survicate"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/swell"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/tatumio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/taxjar"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/teamgate"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/technicalanalysisapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/telegrambottoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/telnyx"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/terraformcloudpersonaltoken"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/text2data"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/textmagic"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/thinkific"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ticketmaster"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/tiingo"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/timezoneapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/tmetric"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/todoist"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/tomorrowio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/tomtom"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/tradier"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/travisci"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/trelloapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/twelvedata"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/twilio"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/tyntec"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/typeform"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/ubidots"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/unifyid"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/unplugg"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/unsplash"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/upcdatabase"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/uplead"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/uri"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/urlscan"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/userstack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/vatlayer"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/vercel"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/verifier"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/verimail"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/veriphone"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/virustotal"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/visualcrossing"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/voicegain"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/vouchery"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/vpnapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/vultrapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/vyte"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/walkscore"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/weatherbit"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/weatherstack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/webex"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/webflow"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/webscraping"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/whoxy"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/workstack"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/worldcoinindex"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/worldweather"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/wrike"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/yandex"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/youneedabudget"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/yousign"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/youtubeapikey"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/zendeskapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/zenscrape"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/zenserp"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/zeplin"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/zerobounce"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/zipapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/zipbooks"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/zipcodeapi"
	"github.com/trufflesecurity/trufflehog/pkg/detectors/zonkafeedback"
)

func DefaultDetectors() []detectors.Detector {
	return []detectors.Detector{
		&heroku.Scanner{},
		&linearapi.Scanner{},
		&alibaba.Scanner{},
		&aws.Scanner{},
		&azure.Scanner{},
		&slack.Scanner{}, // has 4 secret types
		&gitlabv2.Scanner{},
		&gitlab.Scanner{},
		&sendgrid.Scanner{},
		&mailchimp.Scanner{},
		&okta.Scanner{},
		&onelogin.Scanner{},
		&heroku.Scanner{},
		&dropbox.Scanner{},
		&linearapi.Scanner{},
		&stripe.Scanner{},
		&square.Scanner{},
		&squareapp.Scanner{},
		&pivotaltracker.Scanner{},
		&github.Scanner{},
		&twilio.Scanner{},
		&gcp.Scanner{},
		&circleci.Scanner{},
		&uri.Scanner{},
		&razorpay.Scanner{},
		&jdbc.Scanner{},
		&privatekey.Scanner{},
		&maxmindlicense.Scanner{},
		&airtableapikey.Scanner{},
		&bitfinex.Scanner{},
		&telegrambottoken.Scanner{},
		&clarifai.Scanner{},
		&cloudflareapitoken.Scanner{},
		&cloudflarecakey.Scanner{},
		// &cloudflareglobalapikey.Scanner{},
		&terraformcloudpersonaltoken.Scanner{},
		&asanapersonalaccesstoken.Scanner{},
		&trelloapikey.Scanner{},
		&mapbox.Scanner{},
		&mailgun.Scanner{},
		&mailjetbasicauth.Scanner{},
		&auth0managementapitoken.Scanner{},
		// &auth0oauth.Scanner{},
		&mailjetsms.Scanner{},
		&digitaloceantoken.Scanner{},
		&paystack.Scanner{},
		&contentfulpersonalaccesstoken.Scanner{},
		&hunter.Scanner{},
		&sendinbluev2.Scanner{},
		&elasticemail.Scanner{},
		&messagebird.Scanner{},
		&microsoftteamswebhook.Scanner{},
		&plivo.Scanner{},
		&rapidapi.Scanner{},
		&discordbottoken.Scanner{},
		&netlify.Scanner{},
		&hubspotapikey.Scanner{},
		&travisci.Scanner{},
		&scalewaykey.Scanner{},
		&fastlypersonaltoken.Scanner{},
		&snykkey.Scanner{},
		&postmark.Scanner{},
		&figmapersonalaccesstoken.Scanner{},
		&github_old.Scanner{},
		&webex.Scanner{},
		&segmentapikey.Scanner{},
		&vultrapikey.Scanner{},
		// &ibmclouduserkey.Scanner{},
		&pepipost.Scanner{},
		&postman.Scanner{},
		&nexmoapikey.Scanner{},
		&newrelicpersonalapikey.Scanner{},
		&pushbulletapikey.Scanner{},
		&paypaloauth.Scanner{},
		&datadogtoken.Scanner{},
		&airbrakeuserkey.Scanner{},
		&sumologickey.Scanner{},
		&pagerdutyapikey.Scanner{},
		&jiratoken.Scanner{},
		&airbrakeprojectkey.Scanner{},
		&calendlyapikey.Scanner{},
		&bitlyaccesstoken.Scanner{},
		&youtubeapikey.Scanner{},
		&coinbase.Scanner{},
		&confluent.Scanner{},
		&zendeskapi.Scanner{},
		&etsyapikey.Scanner{},
		&facebookoauth.Scanner{},
		&amplitudeapikey.Scanner{},
		&pubnubpublishkey.Scanner{},
		&sentrytoken.Scanner{},
		&githubapp.Scanner{},
		&slackwebhook.Scanner{},
		&spotifykey.Scanner{},
		&discordwebhook.Scanner{},
		// &zapierwebhook.Scanner{},
		&pubnubsubscriptionkey.Scanner{},
		// &plaidkey.Scanner{},
		&calendarific.Scanner{},
		&jumpcloud.Scanner{},
		&notion.Scanner{},
		&droneci.Scanner{},
		&ipstack.Scanner{},
		&adobeio.Scanner{},
		&sslmate.Scanner{},
		&buildkite.Scanner{},
		&shodankey.Scanner{},
		&lokalisetoken.Scanner{},
		&twelvedata.Scanner{},
		&intercom.Scanner{},
		&d7network.Scanner{},
		&buttercms.Scanner{},
		&taxjar.Scanner{},
		&zerobounce.Scanner{},
		&fixerio.Scanner{},
		&verimail.Scanner{},
		&helpscout.Scanner{},
		&beamer.Scanner{},
		&liveagent.Scanner{},
		&pipedrive.Scanner{},
		&cannyio.Scanner{},
		&vercel.Scanner{},
		&posthog.Scanner{},
		&mandrill.Scanner{},
		&mailmodo.Scanner{},
		&flutterwave.Scanner{},
		&algoliaadminkey.Scanner{},
		&mattermostpersonaltoken.Scanner{},
		&splunkobservabilitytoken.Scanner{},
		&simvoly.Scanner{},
		&surveysparrow.Scanner{},
		&survicate.Scanner{},
		&omnisend.Scanner{},
		&getgist.Scanner{},
		&groovehq.Scanner{},
		&newsapi.Scanner{},
		&helpcrunch.Scanner{},
		// &linemessaging.Scanner{},
		&launchdarkly.Scanner{},
		&salesflare.Scanner{},
		&chatbot.Scanner{},
		&nftport.Scanner{},
		&coveralls.Scanner{},
		&rubygems.Scanner{},
		&webflow.Scanner{},
		&graphcms.Scanner{},
		&anypoint.Scanner{},
		&frameio.Scanner{},
		&zonkafeedback.Scanner{},
		&surveybot.Scanner{},
		&mailerlite.Scanner{},
		&qualaroo.Scanner{},
		&simplesat.Scanner{},
		&convertkit.Scanner{},
		&clockworksms.Scanner{},
		&apideck.Scanner{},
		&zeplin.Scanner{},
		&myfreshworks.Scanner{},
		&satismeterwritekey.Scanner{},
		&customerio.Scanner{},
		&clicksendsms.Scanner{},
		&copper.Scanner{},
		&skrappio.Scanner{},
		&delighted.Scanner{},
		&abbysale.Scanner{},
		&feedier.Scanner{},
		&prospectio.Scanner{},
		&nytimes.Scanner{},
		&powrbot.Scanner{},
		&magnetic.Scanner{},
		&polygon.Scanner{},
		&smartsheets.Scanner{},
		// &wepay.Scanner{},
		// &artifactory.Scanner{},
		&integromat.Scanner{},
		&linenotify.Scanner{},
		&float.Scanner{},
		&monday.Scanner{},
		// &debounce.Scanner{},
		&guardianapi.Scanner{},
		&squarespace.Scanner{},
		&wrike.Scanner{},
		&storyblok.Scanner{},
		&salesblink.Scanner{},
		&campayn.Scanner{},
		&clinchpad.Scanner{},
		&companyhub.Scanner{},
		&dyspatch.Scanner{},
		&harvest.Scanner{},
		&moosend.Scanner{},
		&openweather.Scanner{},
		&siteleaf.Scanner{},
		&flowflu.Scanner{},
		&nimble.Scanner{},
		&lessannoyingcrm.Scanner{},
		&nethunt.Scanner{},
		&apptivo.Scanner{},
		&capsulecrm.Scanner{},
		&insightly.Scanner{},
		&kylas.Scanner{},
		&onepagecrm.Scanner{},
		&reallysimplesystems.Scanner{},
		&timezoneapi.Scanner{},
		&everhour.Scanner{},
		&jotform.Scanner{},
		&workstack.Scanner{},
		&clockify.Scanner{},
		&karmacrm.Scanner{},
		&revampcrm.Scanner{},
		&apollo.Scanner{},
		&artsy.Scanner{},
		&vpnapi.Scanner{},
		&dnscheck.Scanner{},
		// &toggltrack.Scanner{},
		&ethplorer.Scanner{},
		&fulcrum.Scanner{},
		&metrilo.Scanner{},
		&salescookie.Scanner{},
		&geoipifi.Scanner{},
		&yandex.Scanner{},
		&airship.Scanner{},
		&refiner.Scanner{},
		&pandadoc.Scanner{},
		&juro.Scanner{},
		&documo.Scanner{},
		&roninapp.Scanner{},
		&doppler.Scanner{},
		&codacy.Scanner{},
		&gocardless.Scanner{},
		&alconost.Scanner{},
		&rawg.Scanner{},
		&opengraphr.Scanner{},
		&accuweather.Scanner{},
		&tomtom.Scanner{},
		&teamgate.Scanner{},
		&bulbul.Scanner{},
		&centralstationcrm.Scanner{},
		&tyntec.Scanner{},
		&axonaut.Scanner{},
		&kraken.Scanner{},
		&easyinsight.Scanner{},
		&closecrm.Scanner{},
		&customerguru.Scanner{},
		&prospectcrm.Scanner{},
		&surveyanyplace.Scanner{},
		&ubidots.Scanner{},
		sinchmessage.Scanner{},
		ayrshare.Scanner{},
		mailboxlayer.Scanner{},
		satismeterprojectkey.Scanner{},
		pusherchannelkey.Scanner{},
		imagekit.Scanner{},
		asanaoauth.Scanner{},
		getemail.Scanner{},
		rocketreach.Scanner{},
		// raven.Scanner{},
		kontent.Scanner{},
		cloudplan.Scanner{},
		autoklose.Scanner{},
		appcues.Scanner{},
		getemails.Scanner{},
		leadfeeder.Scanner{},
		uplead.Scanner{},
		audd.Scanner{},
		bitbar.Scanner{},
		// abstract.Scanner{},
		exchangerateapi.Scanner{},
		currencycloud.Scanner{},
		finage.Scanner{},
		adafruitio.Scanner{},
		storychief.Scanner{},
		tradier.Scanner{},
		hellosign.Scanner{},
		dwolla.Scanner{},
		voicegain.Scanner{},
		ambee.Scanner{},
		bannerbear.Scanner{},
		hypertrack.Scanner{},
		holidayapi.Scanner{},
		lastfm.Scanner{},
		currencylayer.Scanner{},
		coinlib.Scanner{},
		agora.Scanner{},
		marketstack.Scanner{},
		exchangeratesapi.Scanner{},
		faceplusplus.Scanner{},
		baremetrics.Scanner{},
		getgeoapi.Scanner{},
		alegra.Scanner{},
		tatumio.Scanner{},
		deepgram.Scanner{},
		brandfetch.Scanner{},
		typeform.Scanner{},
		blablabus.Scanner{},
		fxmarket.Scanner{},
		ipapi.Scanner{},
		clearbit.Scanner{},
		spoonacular.Scanner{},
		finnhub.Scanner{},
		checkout.Scanner{},
		mixpanel.Scanner{},
		ipgeolocation.Scanner{},
		tmetric.Scanner{},
		fullstory.Scanner{},
		noticeable.Scanner{},
		currencyscoop.Scanner{},
		scrapingbee.Scanner{},
		todoist.Scanner{},
		owlbot.Scanner{},
		keenio.Scanner{},
		dovico.Scanner{},
		html2pdf.Scanner{},
		yousign.Scanner{},
		fleetbase.Scanner{},
		cloudmersive.Scanner{},
		imagga.Scanner{},
		visualcrossing.Scanner{},
		bugsnag.Scanner{},
		runrunit.Scanner{},
		assemblyai.Scanner{},
		loyverse.Scanner{},
		swell.Scanner{},
		crowdin.Scanner{},
		nutritionix.Scanner{},
		mapquest.Scanner{},
		clickuppersonaltoken.Scanner{},
		tiingo.Scanner{},
		billomat.Scanner{},
		blogger.Scanner{},
		front.Scanner{},
		nitro.Scanner{},
		apify.Scanner{},
		dynalist.Scanner{},
		mavenlink.Scanner{},
		sportsmonk.Scanner{},
		bitcoinaverage.Scanner{},
		zipcodeapi.Scanner{},
		gyazo.Scanner{},
		fakejson.Scanner{},
		sparkpost.Scanner{},
		locationiq.Scanner{},
		saucelabs.Scanner{},
		enigma.Scanner{},
		clickhelp.Scanner{},
		adzuna.Scanner{},
		vouchery.Scanner{},
		currentsapi.Scanner{},
		flickr.Scanner{},
		apiflash.Scanner{},
		geocodio.Scanner{},
		datagov.Scanner{},
		tomorrowio.Scanner{},
		lexigram.Scanner{},
		securitytrails.Scanner{},
		foursquare.Scanner{},
		browshot.Scanner{},
		edamam.Scanner{},
		alienvault.Scanner{},
		protocolsio.Scanner{},
		coinlayer.Scanner{},
		commercejs.Scanner{},
		detectlanguage.Scanner{},
		worldcoinindex.Scanner{},
		airvisual.Scanner{},
		sheety.Scanner{},
		financialmodelingprep.Scanner{},
		stormglass.Scanner{},
		oopspam.Scanner{},
		unsplash.Scanner{},
		allsports.Scanner{},
		amadeus.Scanner{},
		ringcentral.Scanner{},
		pixabay.Scanner{},
		ipify.Scanner{},
		youneedabudget.Scanner{},
		macaddress.Scanner{},
		languagelayer.Scanner{},
		gengo.Scanner{},
		aylien.Scanner{},
		shutterstock.Scanner{},
		hereapi.Scanner{},
		text2data.Scanner{},
		readme.Scanner{},
		pastebin.Scanner{},
		vatlayer.Scanner{},
		verifier.Scanner{},
		onwaterio.Scanner{},
		graphhopper.Scanner{},
		scraperapi.Scanner{},
		ritekit.Scanner{},
		linkpreview.Scanner{},
		dotmailer.Scanner{},
		api2cart.Scanner{},
		virustotal.Scanner{},
		numverify.Scanner{},
		pdflayer.Scanner{},
		geocode.Scanner{},
		iconfinder.Scanner{},
		m3o.Scanner{},
		mesibo.Scanner{},
		impala.Scanner{},
		besttime.Scanner{},
		currencyfreaks.Scanner{},
		humanity.Scanner{},
		loginradius.Scanner{},
		stockdata.Scanner{},
		flatio.Scanner{},
		openuv.Scanner{},
		snipcart.Scanner{},
		screenshotapi.Scanner{},
		cryptocompare.Scanner{},
		happyscribe.Scanner{},
		geocodify.Scanner{},
		bombbomb.Scanner{},
		serpstack.Scanner{},
		zenserp.Scanner{},
		restpackscreenshotapi.Scanner{},
		shortcut.Scanner{},
		nasdaqdatalink.Scanner{},
		quickmetrics.Scanner{},
		neutrinoapi.Scanner{},
		bitmex.Scanner{},
		deepai.Scanner{},
		host.Scanner{},
		pdfshift.Scanner{},
		fetchrss.Scanner{},
		proxycrawl.Scanner{},
		storecove.Scanner{},
		fileio.Scanner{},
		coinapi.Scanner{},
		stytch.Scanner{},
		signupgenius.Scanner{},
		streak.Scanner{},
		route4me.Scanner{},
		opencagedata.Scanner{},
		positionstack.Scanner{},
		upcdatabase.Scanner{},
		commodities.Scanner{},
		glassnode.Scanner{},
		optimizely.Scanner{},
		censys.Scanner{},
		scraperbox.Scanner{},
		passbase.Scanner{},
		ticketmaster.Scanner{},
		datafire.Scanner{},
		iexcloud.Scanner{},
		partnerstack.Scanner{},
		qubole.Scanner{},
		poloniex.Scanner{},
		shipday.Scanner{},
		stitchdata.Scanner{},
		hiveage.Scanner{},
		technicalanalysisapi.Scanner{},
		smartystreets.Scanner{},
		shutterstockoauth.Scanner{},
		newscatcher.Scanner{},
		postageapp.Scanner{},
		unplugg.Scanner{},
		paymongo.Scanner{},
		flightapi.Scanner{},
		countrylayer.Scanner{},
		veriphone.Scanner{},
		ipinfodb.Scanner{},
		mediastack.Scanner{},
		screenshotlayer.Scanner{},
		userstack.Scanner{},
		edenai.Scanner{},
		urlscan.Scanner{},
		zenscrape.Scanner{},
		dailyco.Scanner{},
		nicereply.Scanner{},
		hive.Scanner{},
		clustdoc.Scanner{},
		scrapingant.Scanner{},
		kickbox.Scanner{},
		scrapeowl.Scanner{},
		rebrandly.Scanner{},
		dandelion.Scanner{},
		baseapiio.Scanner{},
		purestake.Scanner{},
		carboninterface.Scanner{},
		signaturit.Scanner{},
		blitapp.Scanner{},
		restpackhtmltopdfapi.Scanner{},
		webscraping.Scanner{},
		sentiment.Scanner{},
		geoapify.Scanner{},
		dfuse.Scanner{},
		gitter.Scanner{},
		autopilot.Scanner{},
		aletheiaapi.Scanner{},
		intrinio.Scanner{},
		aviationstack.Scanner{},
		scrapestack.Scanner{},
		restpack.Scanner{},
		cloverly.Scanner{},
		thinkific.Scanner{},
		meaningcloud.Scanner{},
		skybiometry.Scanner{},
		appfollow.Scanner{},
		abuseipdb.Scanner{},
		squareup.Scanner{},
		zipbooks.Scanner{},
		roaring.Scanner{},
		signalwire.Scanner{},
		weatherbit.Scanner{},
		textmagic.Scanner{},
		telnyx.Scanner{},
		calorieninja.Scanner{},
		vyte.Scanner{},
		walkscore.Scanner{},
		planyo.Scanner{},
		zipapi.Scanner{},
		mailsac.Scanner{},
		unifyid.Scanner{},
		worldweather.Scanner{},
		strava.Scanner{},
		autodesk.Scanner{},
		serphouse.Scanner{},
		paralleldots.Scanner{},
		semaphore.Scanner{},
		nylas.Scanner{},
		weatherstack.Scanner{},
		ipquality.Scanner{},
		blazemeter.Scanner{},
		cicero.Scanner{},
		onedesk.Scanner{},
		bugherd.Scanner{},
		whoxy.Scanner{},
		smooch.Scanner{},
		apifonica.Scanner{},
	}
}
