// Code generated by go generate; DO NOT EDIT.
package square

import "errors"

type Permission int

const (
    Invalid Permission = iota
    BankAccountsRead Permission = iota
    AppointmentsWrite Permission = iota
    AppointmentsAllWrite Permission = iota
    AppointmentsRead Permission = iota
    AppointmentsAllRead Permission = iota
    AppointmentsBusinessSettingsRead Permission = iota
    PaymentsRead Permission = iota
    PaymentsWrite Permission = iota
    CashDrawerRead Permission = iota
    ItemsWrite Permission = iota
    ItemsRead Permission = iota
    OrdersWrite Permission = iota
    OrdersRead Permission = iota
    CustomersWrite Permission = iota
    CustomersRead Permission = iota
    DeviceCredentialManagement Permission = iota
    DevicesRead Permission = iota
    DisputesWrite Permission = iota
    DisputesRead Permission = iota
    EmployeesRead Permission = iota
    GiftcardsRead Permission = iota
    GiftcardsWrite Permission = iota
    InventoryWrite Permission = iota
    InventoryRead Permission = iota
    InvoicesWrite Permission = iota
    InvoicesRead Permission = iota
    TimecardsSettingsWrite Permission = iota
    TimecardsWrite Permission = iota
    TimecardsSettingsRead Permission = iota
    TimecardsRead Permission = iota
    MerchantProfileWrite Permission = iota
    MerchantProfileRead Permission = iota
    LoyaltyRead Permission = iota
    LoyaltyWrite Permission = iota
    PaymentsWriteInPerson Permission = iota
    PaymentsWriteSharedOnfile Permission = iota
    PaymentsWriteAdditionalRecipients Permission = iota
    PayoutsRead Permission = iota
    OnlineStoreSiteRead Permission = iota
    OnlineStoreSnippetsWrite Permission = iota
    OnlineStoreSnippetsRead Permission = iota
    SubscriptionsWrite Permission = iota
    SubscriptionsRead Permission = iota
)

var (
    PermissionStrings = map[Permission]string{
        BankAccountsRead: "BANK_ACCOUNTS_READ",
        AppointmentsWrite: "APPOINTMENTS_WRITE",
        AppointmentsAllWrite: "APPOINTMENTS_ALL_WRITE",
        AppointmentsRead: "APPOINTMENTS_READ",
        AppointmentsAllRead: "APPOINTMENTS_ALL_READ",
        AppointmentsBusinessSettingsRead: "APPOINTMENTS_BUSINESS_SETTINGS_READ",
        PaymentsRead: "PAYMENTS_READ",
        PaymentsWrite: "PAYMENTS_WRITE",
        CashDrawerRead: "CASH_DRAWER_READ",
        ItemsWrite: "ITEMS_WRITE",
        ItemsRead: "ITEMS_READ",
        OrdersWrite: "ORDERS_WRITE",
        OrdersRead: "ORDERS_READ",
        CustomersWrite: "CUSTOMERS_WRITE",
        CustomersRead: "CUSTOMERS_READ",
        DeviceCredentialManagement: "DEVICE_CREDENTIAL_MANAGEMENT",
        DevicesRead: "DEVICES_READ",
        DisputesWrite: "DISPUTES_WRITE",
        DisputesRead: "DISPUTES_READ",
        EmployeesRead: "EMPLOYEES_READ",
        GiftcardsRead: "GIFTCARDS_READ",
        GiftcardsWrite: "GIFTCARDS_WRITE",
        InventoryWrite: "INVENTORY_WRITE",
        InventoryRead: "INVENTORY_READ",
        InvoicesWrite: "INVOICES_WRITE",
        InvoicesRead: "INVOICES_READ",
        TimecardsSettingsWrite: "TIMECARDS_SETTINGS_WRITE",
        TimecardsWrite: "TIMECARDS_WRITE",
        TimecardsSettingsRead: "TIMECARDS_SETTINGS_READ",
        TimecardsRead: "TIMECARDS_READ",
        MerchantProfileWrite: "MERCHANT_PROFILE_WRITE",
        MerchantProfileRead: "MERCHANT_PROFILE_READ",
        LoyaltyRead: "LOYALTY_READ",
        LoyaltyWrite: "LOYALTY_WRITE",
        PaymentsWriteInPerson: "PAYMENTS_WRITE_IN_PERSON",
        PaymentsWriteSharedOnfile: "PAYMENTS_WRITE_SHARED_ONFILE",
        PaymentsWriteAdditionalRecipients: "PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS",
        PayoutsRead: "PAYOUTS_READ",
        OnlineStoreSiteRead: "ONLINE_STORE_SITE_READ",
        OnlineStoreSnippetsWrite: "ONLINE_STORE_SNIPPETS_WRITE",
        OnlineStoreSnippetsRead: "ONLINE_STORE_SNIPPETS_READ",
        SubscriptionsWrite: "SUBSCRIPTIONS_WRITE",
        SubscriptionsRead: "SUBSCRIPTIONS_READ",
    }

    StringToPermission = map[string]Permission{
        "BANK_ACCOUNTS_READ": BankAccountsRead,
        "APPOINTMENTS_WRITE": AppointmentsWrite,
        "APPOINTMENTS_ALL_WRITE": AppointmentsAllWrite,
        "APPOINTMENTS_READ": AppointmentsRead,
        "APPOINTMENTS_ALL_READ": AppointmentsAllRead,
        "APPOINTMENTS_BUSINESS_SETTINGS_READ": AppointmentsBusinessSettingsRead,
        "PAYMENTS_READ": PaymentsRead,
        "PAYMENTS_WRITE": PaymentsWrite,
        "CASH_DRAWER_READ": CashDrawerRead,
        "ITEMS_WRITE": ItemsWrite,
        "ITEMS_READ": ItemsRead,
        "ORDERS_WRITE": OrdersWrite,
        "ORDERS_READ": OrdersRead,
        "CUSTOMERS_WRITE": CustomersWrite,
        "CUSTOMERS_READ": CustomersRead,
        "DEVICE_CREDENTIAL_MANAGEMENT": DeviceCredentialManagement,
        "DEVICES_READ": DevicesRead,
        "DISPUTES_WRITE": DisputesWrite,
        "DISPUTES_READ": DisputesRead,
        "EMPLOYEES_READ": EmployeesRead,
        "GIFTCARDS_READ": GiftcardsRead,
        "GIFTCARDS_WRITE": GiftcardsWrite,
        "INVENTORY_WRITE": InventoryWrite,
        "INVENTORY_READ": InventoryRead,
        "INVOICES_WRITE": InvoicesWrite,
        "INVOICES_READ": InvoicesRead,
        "TIMECARDS_SETTINGS_WRITE": TimecardsSettingsWrite,
        "TIMECARDS_WRITE": TimecardsWrite,
        "TIMECARDS_SETTINGS_READ": TimecardsSettingsRead,
        "TIMECARDS_READ": TimecardsRead,
        "MERCHANT_PROFILE_WRITE": MerchantProfileWrite,
        "MERCHANT_PROFILE_READ": MerchantProfileRead,
        "LOYALTY_READ": LoyaltyRead,
        "LOYALTY_WRITE": LoyaltyWrite,
        "PAYMENTS_WRITE_IN_PERSON": PaymentsWriteInPerson,
        "PAYMENTS_WRITE_SHARED_ONFILE": PaymentsWriteSharedOnfile,
        "PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS": PaymentsWriteAdditionalRecipients,
        "PAYOUTS_READ": PayoutsRead,
        "ONLINE_STORE_SITE_READ": OnlineStoreSiteRead,
        "ONLINE_STORE_SNIPPETS_WRITE": OnlineStoreSnippetsWrite,
        "ONLINE_STORE_SNIPPETS_READ": OnlineStoreSnippetsRead,
        "SUBSCRIPTIONS_WRITE": SubscriptionsWrite,
        "SUBSCRIPTIONS_READ": SubscriptionsRead,
    }

    PermissionIDs = map[Permission]int{
        BankAccountsRead: 1,
        AppointmentsWrite: 2,
        AppointmentsAllWrite: 3,
        AppointmentsRead: 4,
        AppointmentsAllRead: 5,
        AppointmentsBusinessSettingsRead: 6,
        PaymentsRead: 7,
        PaymentsWrite: 8,
        CashDrawerRead: 9,
        ItemsWrite: 10,
        ItemsRead: 11,
        OrdersWrite: 12,
        OrdersRead: 13,
        CustomersWrite: 14,
        CustomersRead: 15,
        DeviceCredentialManagement: 16,
        DevicesRead: 17,
        DisputesWrite: 18,
        DisputesRead: 19,
        EmployeesRead: 20,
        GiftcardsRead: 21,
        GiftcardsWrite: 22,
        InventoryWrite: 23,
        InventoryRead: 24,
        InvoicesWrite: 25,
        InvoicesRead: 26,
        TimecardsSettingsWrite: 27,
        TimecardsWrite: 28,
        TimecardsSettingsRead: 29,
        TimecardsRead: 30,
        MerchantProfileWrite: 31,
        MerchantProfileRead: 32,
        LoyaltyRead: 33,
        LoyaltyWrite: 34,
        PaymentsWriteInPerson: 35,
        PaymentsWriteSharedOnfile: 36,
        PaymentsWriteAdditionalRecipients: 37,
        PayoutsRead: 38,
        OnlineStoreSiteRead: 39,
        OnlineStoreSnippetsWrite: 40,
        OnlineStoreSnippetsRead: 41,
        SubscriptionsWrite: 42,
        SubscriptionsRead: 43,
    }

    IdToPermission = map[int]Permission{
        1: BankAccountsRead,
        2: AppointmentsWrite,
        3: AppointmentsAllWrite,
        4: AppointmentsRead,
        5: AppointmentsAllRead,
        6: AppointmentsBusinessSettingsRead,
        7: PaymentsRead,
        8: PaymentsWrite,
        9: CashDrawerRead,
        10: ItemsWrite,
        11: ItemsRead,
        12: OrdersWrite,
        13: OrdersRead,
        14: CustomersWrite,
        15: CustomersRead,
        16: DeviceCredentialManagement,
        17: DevicesRead,
        18: DisputesWrite,
        19: DisputesRead,
        20: EmployeesRead,
        21: GiftcardsRead,
        22: GiftcardsWrite,
        23: InventoryWrite,
        24: InventoryRead,
        25: InvoicesWrite,
        26: InvoicesRead,
        27: TimecardsSettingsWrite,
        28: TimecardsWrite,
        29: TimecardsSettingsRead,
        30: TimecardsRead,
        31: MerchantProfileWrite,
        32: MerchantProfileRead,
        33: LoyaltyRead,
        34: LoyaltyWrite,
        35: PaymentsWriteInPerson,
        36: PaymentsWriteSharedOnfile,
        37: PaymentsWriteAdditionalRecipients,
        38: PayoutsRead,
        39: OnlineStoreSiteRead,
        40: OnlineStoreSnippetsWrite,
        41: OnlineStoreSnippetsRead,
        42: SubscriptionsWrite,
        43: SubscriptionsRead,
    }
)

// ToString converts a Permission enum to its string representation
func (p Permission) ToString() (string, error) {
    if str, ok := PermissionStrings[p]; ok {
        return str, nil
    }
    return "", errors.New("invalid permission")
}

// ToID converts a Permission enum to its ID
func (p Permission) ToID() (int, error) {
    if id, ok := PermissionIDs[p]; ok {
        return id, nil
    }
    return 0, errors.New("invalid permission")
}

// PermissionFromString converts a string representation to its Permission enum
func PermissionFromString(s string) (Permission, error) {
    if p, ok := StringToPermission[s]; ok {
        return p, nil
    }
    return 0, errors.New("invalid permission string")
}

// PermissionFromID converts an ID to its Permission enum
func PermissionFromID(id int) (Permission, error) {
    if p, ok := IdToPermission[id]; ok {
        return p, nil
    }
    return 0, errors.New("invalid permission ID")
}
