// Code generated by go generate; DO NOT EDIT.
package slack

import "errors"

type Permission int

const (
    Invalid Permission = iota
    AdminAnalyticsRead Permission = iota
    AdminAnalyticsGetfile Permission = iota
    AdminAppActivitiesRead Permission = iota
    AdminAppsActivitiesList Permission = iota
    AdminAppsWrite Permission = iota
    AdminAppsApprove Permission = iota
    AdminAppsClearresolution Permission = iota
    AdminAppsConfigSet Permission = iota
    AdminAppsRequestsCancel Permission = iota
    AdminAppsRestrict Permission = iota
    AdminAppsUninstall Permission = iota
    AdminAppsRead Permission = iota
    AdminAppsApprovedList Permission = iota
    AdminAppsConfigLookup Permission = iota
    AdminAppsRequestsList Permission = iota
    AdminAppsRestrictedList Permission = iota
    AdminUsersWrite Permission = iota
    AdminAuthPolicyAssignentities Permission = iota
    AdminAuthPolicyRemoveentities Permission = iota
    AdminUsersAssign Permission = iota
    AdminUsersInvite Permission = iota
    AdminUsersRemove Permission = iota
    AdminUsersSessionClearsettings Permission = iota
    AdminUsersSessionInvalidate Permission = iota
    AdminUsersSessionReset Permission = iota
    AdminUsersSessionResetbulk Permission = iota
    AdminUsersSessionSetsettings Permission = iota
    AdminUsersSetadmin Permission = iota
    AdminUsersSetexpiration Permission = iota
    AdminUsersSetowner Permission = iota
    AdminUsersSetregular Permission = iota
    AdminUsersRead Permission = iota
    AdminAuthPolicyGetentities Permission = iota
    AdminUsersList Permission = iota
    AdminUsersSessionGetsettings Permission = iota
    AdminUsersSessionList Permission = iota
    AdminUsersUnsupportedversionsExport Permission = iota
    AdminBarriersWrite Permission = iota
    AdminBarriersCreate Permission = iota
    AdminBarriersDelete Permission = iota
    AdminBarriersUpdate Permission = iota
    AdminBarriersRead Permission = iota
    AdminBarriersList Permission = iota
    AdminConversationsWrite Permission = iota
    AdminConversationsArchive Permission = iota
    AdminConversationsBulkarchive Permission = iota
    AdminConversationsBulkdelete Permission = iota
    AdminConversationsBulkmove Permission = iota
    AdminConversationsConverttoprivate Permission = iota
    AdminConversationsConverttopublic Permission = iota
    AdminConversationsCreate Permission = iota
    AdminConversationsDelete Permission = iota
    AdminConversationsDisconnectshared Permission = iota
    AdminConversationsInvite Permission = iota
    AdminConversationsRemovecustomretention Permission = iota
    AdminConversationsRename Permission = iota
    AdminConversationsRestrictaccessAddgroup Permission = iota
    AdminConversationsRestrictaccessRemovegroup Permission = iota
    AdminConversationsSetconversationprefs Permission = iota
    AdminConversationsSetcustomretention Permission = iota
    AdminConversationsSetteams Permission = iota
    AdminConversationsUnarchive Permission = iota
    AdminConversationsRead Permission = iota
    AdminConversationsEkmListoriginalconnectedchannelinfo Permission = iota
    AdminConversationsGetconversationprefs Permission = iota
    AdminConversationsGetcustomretention Permission = iota
    AdminConversationsGetteams Permission = iota
    AdminConversationsLookup Permission = iota
    AdminConversationsRestrictaccessListgroups Permission = iota
    AdminConversationsSearch Permission = iota
    AdminTeamsWrite Permission = iota
    AdminEmojiAdd Permission = iota
    AdminEmojiAddalias Permission = iota
    AdminEmojiRemove Permission = iota
    AdminTeamsCreate Permission = iota
    AdminTeamsSettingsSetdefaultchannels Permission = iota
    AdminTeamsSettingsSetdescription Permission = iota
    AdminTeamsSettingsSetdiscoverability Permission = iota
    AdminTeamsSettingsSeticon Permission = iota
    AdminTeamsSettingsSetname Permission = iota
    AdminUsergroupsAddteams Permission = iota
    AdminTeamsRead Permission = iota
    AdminEmojiList Permission = iota
    AdminTeamsAdminsList Permission = iota
    AdminTeamsList Permission = iota
    AdminTeamsOwnersList Permission = iota
    AdminTeamsSettingsInfo Permission = iota
    AdminWorkflowsRead Permission = iota
    AdminFunctionsList Permission = iota
    AdminFunctionsPermissionsLookup Permission = iota
    AdminWorkflowsPermissionsLookup Permission = iota
    AdminWorkflowsSearch Permission = iota
    AdminWorkflowsWrite Permission = iota
    AdminFunctionsPermissionsSet Permission = iota
    AdminWorkflowsCollaboratorsAdd Permission = iota
    AdminWorkflowsCollaboratorsRemove Permission = iota
    AdminWorkflowsUnpublish Permission = iota
    AdminInvitesWrite Permission = iota
    AdminInviterequestsApprove Permission = iota
    AdminInviterequestsDeny Permission = iota
    AdminInvitesRead Permission = iota
    AdminInviterequestsApprovedList Permission = iota
    AdminInviterequestsDeniedList Permission = iota
    AdminInviterequestsList Permission = iota
    AdminRolesWrite Permission = iota
    AdminRolesAddassignments Permission = iota
    AdminRolesRemoveassignments Permission = iota
    AdminRolesRead Permission = iota
    AdminRolesListassignments Permission = iota
    AdminUsergroupsWrite Permission = iota
    AdminUsergroupsAddchannels Permission = iota
    AdminUsergroupsRemovechannels Permission = iota
    AdminUsergroupsRead Permission = iota
    AdminUsergroupsListchannels Permission = iota
    HostingRead Permission = iota
    AppsActivitiesList Permission = iota
    ConnectionsWrite Permission = iota
    AppsConnectionsOpen Permission = iota
    Token Permission = iota
    AppsDatastoreBulkdelete Permission = iota
    AppsDatastoreBulkget Permission = iota
    AppsDatastoreBulkput Permission = iota
    AppsDatastoreDelete Permission = iota
    AppsDatastoreGet Permission = iota
    AppsDatastorePut Permission = iota
    AppsDatastoreQuery Permission = iota
    AppsDatastoreUpdate Permission = iota
    DatastoreRead Permission = iota
    AppsDatastoreCount Permission = iota
    AuthorizationsRead Permission = iota
    AppsEventAuthorizationsList Permission = iota
    Bot Permission = iota
    AuthRevoke Permission = iota
    AuthTest Permission = iota
    ChatGetpermalink Permission = iota
    ChatScheduledmessagesList Permission = iota
    DialogOpen Permission = iota
    FunctionsCompleteerror Permission = iota
    FunctionsCompletesuccess Permission = iota
    RtmConnect Permission = iota
    RtmStart Permission = iota
    ViewsOpen Permission = iota
    ViewsPublish Permission = iota
    ViewsPush Permission = iota
    ViewsUpdate Permission = iota
    BookmarksWrite Permission = iota
    BookmarksAdd Permission = iota
    BookmarksEdit Permission = iota
    BookmarksRemove Permission = iota
    BookmarksRead Permission = iota
    BookmarksList Permission = iota
    UsersRead Permission = iota
    BotsInfo Permission = iota
    UsersGetpresence Permission = iota
    UsersInfo Permission = iota
    UsersList Permission = iota
    CallsWrite Permission = iota
    CallsAdd Permission = iota
    CallsEnd Permission = iota
    CallsParticipantsAdd Permission = iota
    CallsParticipantsRemove Permission = iota
    CallsUpdate Permission = iota
    CallsRead Permission = iota
    CallsInfo Permission = iota
    ChannelsManage Permission = iota
    ChannelsCreate Permission = iota
    ChannelsMark Permission = iota
    ConversationsArchive Permission = iota
    ConversationsClose Permission = iota
    ConversationsCreate Permission = iota
    ConversationsKick Permission = iota
    ConversationsLeave Permission = iota
    ConversationsMark Permission = iota
    ConversationsOpen Permission = iota
    ConversationsRename Permission = iota
    ConversationsUnarchive Permission = iota
    GroupsCreate Permission = iota
    GroupsMark Permission = iota
    ImMark Permission = iota
    ImOpen Permission = iota
    MpimMark Permission = iota
    MpimOpen Permission = iota
    ChannelsRead Permission = iota
    ChannelsInfo Permission = iota
    ConversationsInfo Permission = iota
    ConversationsList Permission = iota
    ConversationsMembers Permission = iota
    GroupsInfo Permission = iota
    ImList Permission = iota
    MpimList Permission = iota
    UsersConversations Permission = iota
    ChannelsWriteInvites Permission = iota
    ChannelsInvite Permission = iota
    ConversationsInvite Permission = iota
    GroupsInvite Permission = iota
    ChatWrite Permission = iota
    ChatDelete Permission = iota
    ChatDeletescheduledmessage Permission = iota
    ChatMemessage Permission = iota
    ChatPostephemeral Permission = iota
    ChatPostmessage Permission = iota
    ChatSchedulemessage Permission = iota
    ChatUpdate Permission = iota
    LinksWrite Permission = iota
    ChatUnfurl Permission = iota
    ConversationsConnectWrite Permission = iota
    ConversationsAcceptsharedinvite Permission = iota
    ConversationsInviteshared Permission = iota
    ConversationsConnectManage Permission = iota
    ConversationsApprovesharedinvite Permission = iota
    ConversationsDeclinesharedinvite Permission = iota
    ConversationsListconnectinvites Permission = iota
    ChannelsHistory Permission = iota
    ConversationsHistory Permission = iota
    ConversationsReplies Permission = iota
    ChannelsJoin Permission = iota
    ConversationsJoin Permission = iota
    ChannelsWriteTopic Permission = iota
    ConversationsSetpurpose Permission = iota
    ConversationsSettopic Permission = iota
    DndWrite Permission = iota
    DndEnddnd Permission = iota
    DndEndsnooze Permission = iota
    DndSetsnooze Permission = iota
    DndRead Permission = iota
    DndInfo Permission = iota
    DndTeaminfo Permission = iota
    EmojiRead Permission = iota
    EmojiList Permission = iota
    FilesWrite Permission = iota
    FilesCommentsDelete Permission = iota
    FilesCompleteuploadexternal Permission = iota
    FilesDelete Permission = iota
    FilesGetuploadurlexternal Permission = iota
    FilesRevokepublicurl Permission = iota
    FilesSharedpublicurl Permission = iota
    FilesUpload Permission = iota
    FilesRead Permission = iota
    FilesInfo Permission = iota
    FilesList Permission = iota
    RemoteFilesWrite Permission = iota
    FilesRemoteAdd Permission = iota
    FilesRemoteRemove Permission = iota
    FilesRemoteUpdate Permission = iota
    RemoteFilesRead Permission = iota
    FilesRemoteInfo Permission = iota
    FilesRemoteList Permission = iota
    RemoteFilesShare Permission = iota
    FilesRemoteShare Permission = iota
    AppConfigurationsWrite Permission = iota
    FunctionsDistributionsPermissionsAdd Permission = iota
    FunctionsDistributionsPermissionsRemove Permission = iota
    FunctionsDistributionsPermissionsSet Permission = iota
    AppConfigurationsRead Permission = iota
    FunctionsDistributionsPermissionsList Permission = iota
    Conversations Permission = iota
    GroupsOpen Permission = iota
    TokensBasic Permission = iota
    MigrationExchange Permission = iota
    Email Permission = iota
    OpenidConnectUserinfo Permission = iota
    PinsWrite Permission = iota
    PinsAdd Permission = iota
    PinsRemove Permission = iota
    PinsRead Permission = iota
    PinsList Permission = iota
    ReactionsWrite Permission = iota
    ReactionsAdd Permission = iota
    ReactionsRemove Permission = iota
    ReactionsRead Permission = iota
    ReactionsGet Permission = iota
    ReactionsList Permission = iota
    RemindersWrite Permission = iota
    RemindersAdd Permission = iota
    RemindersComplete Permission = iota
    RemindersDelete Permission = iota
    RemindersRead Permission = iota
    RemindersInfo Permission = iota
    RemindersList Permission = iota
    SearchRead Permission = iota
    SearchAll Permission = iota
    SearchFiles Permission = iota
    SearchMessages Permission = iota
    StarsWrite Permission = iota
    StarsAdd Permission = iota
    StarsRemove Permission = iota
    StarsRead Permission = iota
    StarsList Permission = iota
    Admin Permission = iota
    TeamAccesslogs Permission = iota
    TeamBillableinfo Permission = iota
    TeamIntegrationlogs Permission = iota
    TeamBillingRead Permission = iota
    TeamBillingInfo Permission = iota
    TeamRead Permission = iota
    TeamInfo Permission = iota
    TeamPreferencesRead Permission = iota
    TeamPreferencesList Permission = iota
    UsersProfileRead Permission = iota
    TeamProfileGet Permission = iota
    UsersProfileGet Permission = iota
    UsergroupsWrite Permission = iota
    UsergroupsCreate Permission = iota
    UsergroupsDisable Permission = iota
    UsergroupsEnable Permission = iota
    UsergroupsUpdate Permission = iota
    UsergroupsUsersUpdate Permission = iota
    UsergroupsRead Permission = iota
    UsergroupsList Permission = iota
    UsergroupsUsersList Permission = iota
    UsersProfileWrite Permission = iota
    UsersDeletephoto Permission = iota
    UsersProfileSet Permission = iota
    UsersSetphoto Permission = iota
    IdentityBasic Permission = iota
    UsersIdentity Permission = iota
    UsersReadEmail Permission = iota
    UsersLookupbyemail Permission = iota
    UsersWrite Permission = iota
    UsersSetactive Permission = iota
    UsersSetpresence Permission = iota
    WorkflowStepsExecute Permission = iota
    WorkflowsStepcompleted Permission = iota
    WorkflowsStepfailed Permission = iota
    WorkflowsUpdatestep Permission = iota
    TriggersWrite Permission = iota
    WorkflowsTriggersPermissionsAdd Permission = iota
    WorkflowsTriggersPermissionsRemove Permission = iota
    WorkflowsTriggersPermissionsSet Permission = iota
    TriggersRead Permission = iota
    WorkflowsTriggersPermissionsList Permission = iota
)

var (
    PermissionStrings = map[Permission]string{
        AdminAnalyticsRead: "admin_analytics:read",
        AdminAnalyticsGetfile: "admin_analytics_getFile",
        AdminAppActivitiesRead: "admin_app_activities:read",
        AdminAppsActivitiesList: "admin_apps_activities_list",
        AdminAppsWrite: "admin_apps:write",
        AdminAppsApprove: "admin_apps_approve",
        AdminAppsClearresolution: "admin_apps_clearResolution",
        AdminAppsConfigSet: "admin_apps_config_set",
        AdminAppsRequestsCancel: "admin_apps_requests_cancel",
        AdminAppsRestrict: "admin_apps_restrict",
        AdminAppsUninstall: "admin_apps_uninstall",
        AdminAppsRead: "admin_apps:read",
        AdminAppsApprovedList: "admin_apps_approved_list",
        AdminAppsConfigLookup: "admin_apps_config_lookup",
        AdminAppsRequestsList: "admin_apps_requests_list",
        AdminAppsRestrictedList: "admin_apps_restricted_list",
        AdminUsersWrite: "admin_users:write",
        AdminAuthPolicyAssignentities: "admin_auth_policy_assignEntities",
        AdminAuthPolicyRemoveentities: "admin_auth_policy_removeEntities",
        AdminUsersAssign: "admin_users_assign",
        AdminUsersInvite: "admin_users_invite",
        AdminUsersRemove: "admin_users_remove",
        AdminUsersSessionClearsettings: "admin_users_session_clearSettings",
        AdminUsersSessionInvalidate: "admin_users_session_invalidate",
        AdminUsersSessionReset: "admin_users_session_reset",
        AdminUsersSessionResetbulk: "admin_users_session_resetBulk",
        AdminUsersSessionSetsettings: "admin_users_session_setSettings",
        AdminUsersSetadmin: "admin_users_setAdmin",
        AdminUsersSetexpiration: "admin_users_setExpiration",
        AdminUsersSetowner: "admin_users_setOwner",
        AdminUsersSetregular: "admin_users_setRegular",
        AdminUsersRead: "admin_users:read",
        AdminAuthPolicyGetentities: "admin_auth_policy_getEntities",
        AdminUsersList: "admin_users_list",
        AdminUsersSessionGetsettings: "admin_users_session_getSettings",
        AdminUsersSessionList: "admin_users_session_list",
        AdminUsersUnsupportedversionsExport: "admin_users_unsupportedVersions_export",
        AdminBarriersWrite: "admin_barriers:write",
        AdminBarriersCreate: "admin_barriers_create",
        AdminBarriersDelete: "admin_barriers_delete",
        AdminBarriersUpdate: "admin_barriers_update",
        AdminBarriersRead: "admin_barriers:read",
        AdminBarriersList: "admin_barriers_list",
        AdminConversationsWrite: "admin_conversations:write",
        AdminConversationsArchive: "admin_conversations_archive",
        AdminConversationsBulkarchive: "admin_conversations_bulkArchive",
        AdminConversationsBulkdelete: "admin_conversations_bulkDelete",
        AdminConversationsBulkmove: "admin_conversations_bulkMove",
        AdminConversationsConverttoprivate: "admin_conversations_convertToPrivate",
        AdminConversationsConverttopublic: "admin_conversations_convertToPublic",
        AdminConversationsCreate: "admin_conversations_create",
        AdminConversationsDelete: "admin_conversations_delete",
        AdminConversationsDisconnectshared: "admin_conversations_disconnectShared",
        AdminConversationsInvite: "admin_conversations_invite",
        AdminConversationsRemovecustomretention: "admin_conversations_removeCustomRetention",
        AdminConversationsRename: "admin_conversations_rename",
        AdminConversationsRestrictaccessAddgroup: "admin_conversations_restrictAccess_addGroup",
        AdminConversationsRestrictaccessRemovegroup: "admin_conversations_restrictAccess_removeGroup",
        AdminConversationsSetconversationprefs: "admin_conversations_setConversationPrefs",
        AdminConversationsSetcustomretention: "admin_conversations_setCustomRetention",
        AdminConversationsSetteams: "admin_conversations_setTeams",
        AdminConversationsUnarchive: "admin_conversations_unarchive",
        AdminConversationsRead: "admin_conversations:read",
        AdminConversationsEkmListoriginalconnectedchannelinfo: "admin_conversations_ekm_listOriginalConnectedChannelInfo",
        AdminConversationsGetconversationprefs: "admin_conversations_getConversationPrefs",
        AdminConversationsGetcustomretention: "admin_conversations_getCustomRetention",
        AdminConversationsGetteams: "admin_conversations_getTeams",
        AdminConversationsLookup: "admin_conversations_lookup",
        AdminConversationsRestrictaccessListgroups: "admin_conversations_restrictAccess_listGroups",
        AdminConversationsSearch: "admin_conversations_search",
        AdminTeamsWrite: "admin_teams:write",
        AdminEmojiAdd: "admin_emoji_add",
        AdminEmojiAddalias: "admin_emoji_addAlias",
        AdminEmojiRemove: "admin_emoji_remove",
        AdminTeamsCreate: "admin_teams_create",
        AdminTeamsSettingsSetdefaultchannels: "admin_teams_settings_setDefaultChannels",
        AdminTeamsSettingsSetdescription: "admin_teams_settings_setDescription",
        AdminTeamsSettingsSetdiscoverability: "admin_teams_settings_setDiscoverability",
        AdminTeamsSettingsSeticon: "admin_teams_settings_setIcon",
        AdminTeamsSettingsSetname: "admin_teams_settings_setName",
        AdminUsergroupsAddteams: "admin_usergroups_addTeams",
        AdminTeamsRead: "admin_teams:read",
        AdminEmojiList: "admin_emoji_list",
        AdminTeamsAdminsList: "admin_teams_admins_list",
        AdminTeamsList: "admin_teams_list",
        AdminTeamsOwnersList: "admin_teams_owners_list",
        AdminTeamsSettingsInfo: "admin_teams_settings_info",
        AdminWorkflowsRead: "admin_workflows:read",
        AdminFunctionsList: "admin_functions_list",
        AdminFunctionsPermissionsLookup: "admin_functions_permissions_lookup",
        AdminWorkflowsPermissionsLookup: "admin_workflows_permissions_lookup",
        AdminWorkflowsSearch: "admin_workflows_search",
        AdminWorkflowsWrite: "admin_workflows:write",
        AdminFunctionsPermissionsSet: "admin_functions_permissions_set",
        AdminWorkflowsCollaboratorsAdd: "admin_workflows_collaborators_add",
        AdminWorkflowsCollaboratorsRemove: "admin_workflows_collaborators_remove",
        AdminWorkflowsUnpublish: "admin_workflows_unpublish",
        AdminInvitesWrite: "admin_invites:write",
        AdminInviterequestsApprove: "admin_inviteRequests_approve",
        AdminInviterequestsDeny: "admin_inviteRequests_deny",
        AdminInvitesRead: "admin_invites:read",
        AdminInviterequestsApprovedList: "admin_inviteRequests_approved_list",
        AdminInviterequestsDeniedList: "admin_inviteRequests_denied_list",
        AdminInviterequestsList: "admin_inviteRequests_list",
        AdminRolesWrite: "admin_roles:write",
        AdminRolesAddassignments: "admin_roles_addAssignments",
        AdminRolesRemoveassignments: "admin_roles_removeAssignments",
        AdminRolesRead: "admin_roles:read",
        AdminRolesListassignments: "admin_roles_listAssignments",
        AdminUsergroupsWrite: "admin_usergroups:write",
        AdminUsergroupsAddchannels: "admin_usergroups_addChannels",
        AdminUsergroupsRemovechannels: "admin_usergroups_removeChannels",
        AdminUsergroupsRead: "admin_usergroups:read",
        AdminUsergroupsListchannels: "admin_usergroups_listChannels",
        HostingRead: "hosting:read",
        AppsActivitiesList: "apps_activities_list",
        ConnectionsWrite: "connections:write",
        AppsConnectionsOpen: "apps_connections_open",
        Token: "token",
        AppsDatastoreBulkdelete: "apps_datastore_bulkDelete",
        AppsDatastoreBulkget: "apps_datastore_bulkGet",
        AppsDatastoreBulkput: "apps_datastore_bulkPut",
        AppsDatastoreDelete: "apps_datastore_delete",
        AppsDatastoreGet: "apps_datastore_get",
        AppsDatastorePut: "apps_datastore_put",
        AppsDatastoreQuery: "apps_datastore_query",
        AppsDatastoreUpdate: "apps_datastore_update",
        DatastoreRead: "datastore:read",
        AppsDatastoreCount: "apps_datastore_count",
        AuthorizationsRead: "authorizations:read",
        AppsEventAuthorizationsList: "apps_event_authorizations_list",
        Bot: "bot",
        AuthRevoke: "auth_revoke",
        AuthTest: "auth_test",
        ChatGetpermalink: "chat_getPermalink",
        ChatScheduledmessagesList: "chat_scheduledMessages_list",
        DialogOpen: "dialog_open",
        FunctionsCompleteerror: "functions_completeError",
        FunctionsCompletesuccess: "functions_completeSuccess",
        RtmConnect: "rtm_connect",
        RtmStart: "rtm_start",
        ViewsOpen: "views_open",
        ViewsPublish: "views_publish",
        ViewsPush: "views_push",
        ViewsUpdate: "views_update",
        BookmarksWrite: "bookmarks:write",
        BookmarksAdd: "bookmarks_add",
        BookmarksEdit: "bookmarks_edit",
        BookmarksRemove: "bookmarks_remove",
        BookmarksRead: "bookmarks:read",
        BookmarksList: "bookmarks_list",
        UsersRead: "users:read",
        BotsInfo: "bots_info",
        UsersGetpresence: "users_getPresence",
        UsersInfo: "users_info",
        UsersList: "users_list",
        CallsWrite: "calls:write",
        CallsAdd: "calls_add",
        CallsEnd: "calls_end",
        CallsParticipantsAdd: "calls_participants_add",
        CallsParticipantsRemove: "calls_participants_remove",
        CallsUpdate: "calls_update",
        CallsRead: "calls:read",
        CallsInfo: "calls_info",
        ChannelsManage: "channels:manage",
        ChannelsCreate: "channels_create",
        ChannelsMark: "channels_mark",
        ConversationsArchive: "conversations_archive",
        ConversationsClose: "conversations_close",
        ConversationsCreate: "conversations_create",
        ConversationsKick: "conversations_kick",
        ConversationsLeave: "conversations_leave",
        ConversationsMark: "conversations_mark",
        ConversationsOpen: "conversations_open",
        ConversationsRename: "conversations_rename",
        ConversationsUnarchive: "conversations_unarchive",
        GroupsCreate: "groups_create",
        GroupsMark: "groups_mark",
        ImMark: "im_mark",
        ImOpen: "im_open",
        MpimMark: "mpim_mark",
        MpimOpen: "mpim_open",
        ChannelsRead: "channels:read",
        ChannelsInfo: "channels_info",
        ConversationsInfo: "conversations_info",
        ConversationsList: "conversations_list",
        ConversationsMembers: "conversations_members",
        GroupsInfo: "groups_info",
        ImList: "im_list",
        MpimList: "mpim_list",
        UsersConversations: "users_conversations",
        ChannelsWriteInvites: "channels:write_invites",
        ChannelsInvite: "channels_invite",
        ConversationsInvite: "conversations_invite",
        GroupsInvite: "groups_invite",
        ChatWrite: "chat:write",
        ChatDelete: "chat_delete",
        ChatDeletescheduledmessage: "chat_deleteScheduledMessage",
        ChatMemessage: "chat_meMessage",
        ChatPostephemeral: "chat_postEphemeral",
        ChatPostmessage: "chat_postMessage",
        ChatSchedulemessage: "chat_scheduleMessage",
        ChatUpdate: "chat_update",
        LinksWrite: "links:write",
        ChatUnfurl: "chat_unfurl",
        ConversationsConnectWrite: "conversations_connect:write",
        ConversationsAcceptsharedinvite: "conversations_acceptSharedInvite",
        ConversationsInviteshared: "conversations_inviteShared",
        ConversationsConnectManage: "conversations_connect:manage",
        ConversationsApprovesharedinvite: "conversations_approveSharedInvite",
        ConversationsDeclinesharedinvite: "conversations_declineSharedInvite",
        ConversationsListconnectinvites: "conversations_listConnectInvites",
        ChannelsHistory: "channels:history",
        ConversationsHistory: "conversations_history",
        ConversationsReplies: "conversations_replies",
        ChannelsJoin: "channels:join",
        ConversationsJoin: "conversations_join",
        ChannelsWriteTopic: "channels:write_topic",
        ConversationsSetpurpose: "conversations_setPurpose",
        ConversationsSettopic: "conversations_setTopic",
        DndWrite: "dnd:write",
        DndEnddnd: "dnd_endDnd",
        DndEndsnooze: "dnd_endSnooze",
        DndSetsnooze: "dnd_setSnooze",
        DndRead: "dnd:read",
        DndInfo: "dnd_info",
        DndTeaminfo: "dnd_teamInfo",
        EmojiRead: "emoji:read",
        EmojiList: "emoji_list",
        FilesWrite: "files:write",
        FilesCommentsDelete: "files_comments_delete",
        FilesCompleteuploadexternal: "files_completeUploadExternal",
        FilesDelete: "files_delete",
        FilesGetuploadurlexternal: "files_getUploadURLExternal",
        FilesRevokepublicurl: "files_revokePublicURL",
        FilesSharedpublicurl: "files_sharedPublicURL",
        FilesUpload: "files_upload",
        FilesRead: "files:read",
        FilesInfo: "files_info",
        FilesList: "files_list",
        RemoteFilesWrite: "remote_files:write",
        FilesRemoteAdd: "files_remote_add",
        FilesRemoteRemove: "files_remote_remove",
        FilesRemoteUpdate: "files_remote_update",
        RemoteFilesRead: "remote_files:read",
        FilesRemoteInfo: "files_remote_info",
        FilesRemoteList: "files_remote_list",
        RemoteFilesShare: "remote_files:share",
        FilesRemoteShare: "files_remote_share",
        AppConfigurationsWrite: "app_configurations:write",
        FunctionsDistributionsPermissionsAdd: "functions_distributions_permissions_add",
        FunctionsDistributionsPermissionsRemove: "functions_distributions_permissions_remove",
        FunctionsDistributionsPermissionsSet: "functions_distributions_permissions_set",
        AppConfigurationsRead: "app_configurations:read",
        FunctionsDistributionsPermissionsList: "functions_distributions_permissions_list",
        Conversations: "conversations",
        GroupsOpen: "groups_open",
        TokensBasic: "tokens_basic",
        MigrationExchange: "migration_exchange",
        Email: "email",
        OpenidConnectUserinfo: "openid_connect_userInfo",
        PinsWrite: "pins:write",
        PinsAdd: "pins_add",
        PinsRemove: "pins_remove",
        PinsRead: "pins:read",
        PinsList: "pins_list",
        ReactionsWrite: "reactions:write",
        ReactionsAdd: "reactions_add",
        ReactionsRemove: "reactions_remove",
        ReactionsRead: "reactions:read",
        ReactionsGet: "reactions_get",
        ReactionsList: "reactions_list",
        RemindersWrite: "reminders:write",
        RemindersAdd: "reminders_add",
        RemindersComplete: "reminders_complete",
        RemindersDelete: "reminders_delete",
        RemindersRead: "reminders:read",
        RemindersInfo: "reminders_info",
        RemindersList: "reminders_list",
        SearchRead: "search:read",
        SearchAll: "search_all",
        SearchFiles: "search_files",
        SearchMessages: "search_messages",
        StarsWrite: "stars:write",
        StarsAdd: "stars_add",
        StarsRemove: "stars_remove",
        StarsRead: "stars:read",
        StarsList: "stars_list",
        Admin: "admin",
        TeamAccesslogs: "team_accessLogs",
        TeamBillableinfo: "team_billableInfo",
        TeamIntegrationlogs: "team_integrationLogs",
        TeamBillingRead: "team_billing:read",
        TeamBillingInfo: "team_billing_info",
        TeamRead: "team:read",
        TeamInfo: "team_info",
        TeamPreferencesRead: "team_preferences:read",
        TeamPreferencesList: "team_preferences_list",
        UsersProfileRead: "users_profile:read",
        TeamProfileGet: "team_profile_get",
        UsersProfileGet: "users_profile_get",
        UsergroupsWrite: "usergroups:write",
        UsergroupsCreate: "usergroups_create",
        UsergroupsDisable: "usergroups_disable",
        UsergroupsEnable: "usergroups_enable",
        UsergroupsUpdate: "usergroups_update",
        UsergroupsUsersUpdate: "usergroups_users_update",
        UsergroupsRead: "usergroups:read",
        UsergroupsList: "usergroups_list",
        UsergroupsUsersList: "usergroups_users_list",
        UsersProfileWrite: "users_profile:write",
        UsersDeletephoto: "users_deletePhoto",
        UsersProfileSet: "users_profile_set",
        UsersSetphoto: "users_setPhoto",
        IdentityBasic: "identity_basic",
        UsersIdentity: "users_identity",
        UsersReadEmail: "users:read_email",
        UsersLookupbyemail: "users_lookupByEmail",
        UsersWrite: "users:write",
        UsersSetactive: "users_setActive",
        UsersSetpresence: "users_setPresence",
        WorkflowStepsExecute: "workflow_steps:execute",
        WorkflowsStepcompleted: "workflows_stepCompleted",
        WorkflowsStepfailed: "workflows_stepFailed",
        WorkflowsUpdatestep: "workflows_updateStep",
        TriggersWrite: "triggers:write",
        WorkflowsTriggersPermissionsAdd: "workflows_triggers_permissions_add",
        WorkflowsTriggersPermissionsRemove: "workflows_triggers_permissions_remove",
        WorkflowsTriggersPermissionsSet: "workflows_triggers_permissions_set",
        TriggersRead: "triggers:read",
        WorkflowsTriggersPermissionsList: "workflows_triggers_permissions_list",
    }

    StringToPermission = map[string]Permission{
        "admin_analytics:read": AdminAnalyticsRead,
        "admin_analytics_getFile": AdminAnalyticsGetfile,
        "admin_app_activities:read": AdminAppActivitiesRead,
        "admin_apps_activities_list": AdminAppsActivitiesList,
        "admin_apps:write": AdminAppsWrite,
        "admin_apps_approve": AdminAppsApprove,
        "admin_apps_clearResolution": AdminAppsClearresolution,
        "admin_apps_config_set": AdminAppsConfigSet,
        "admin_apps_requests_cancel": AdminAppsRequestsCancel,
        "admin_apps_restrict": AdminAppsRestrict,
        "admin_apps_uninstall": AdminAppsUninstall,
        "admin_apps:read": AdminAppsRead,
        "admin_apps_approved_list": AdminAppsApprovedList,
        "admin_apps_config_lookup": AdminAppsConfigLookup,
        "admin_apps_requests_list": AdminAppsRequestsList,
        "admin_apps_restricted_list": AdminAppsRestrictedList,
        "admin_users:write": AdminUsersWrite,
        "admin_auth_policy_assignEntities": AdminAuthPolicyAssignentities,
        "admin_auth_policy_removeEntities": AdminAuthPolicyRemoveentities,
        "admin_users_assign": AdminUsersAssign,
        "admin_users_invite": AdminUsersInvite,
        "admin_users_remove": AdminUsersRemove,
        "admin_users_session_clearSettings": AdminUsersSessionClearsettings,
        "admin_users_session_invalidate": AdminUsersSessionInvalidate,
        "admin_users_session_reset": AdminUsersSessionReset,
        "admin_users_session_resetBulk": AdminUsersSessionResetbulk,
        "admin_users_session_setSettings": AdminUsersSessionSetsettings,
        "admin_users_setAdmin": AdminUsersSetadmin,
        "admin_users_setExpiration": AdminUsersSetexpiration,
        "admin_users_setOwner": AdminUsersSetowner,
        "admin_users_setRegular": AdminUsersSetregular,
        "admin_users:read": AdminUsersRead,
        "admin_auth_policy_getEntities": AdminAuthPolicyGetentities,
        "admin_users_list": AdminUsersList,
        "admin_users_session_getSettings": AdminUsersSessionGetsettings,
        "admin_users_session_list": AdminUsersSessionList,
        "admin_users_unsupportedVersions_export": AdminUsersUnsupportedversionsExport,
        "admin_barriers:write": AdminBarriersWrite,
        "admin_barriers_create": AdminBarriersCreate,
        "admin_barriers_delete": AdminBarriersDelete,
        "admin_barriers_update": AdminBarriersUpdate,
        "admin_barriers:read": AdminBarriersRead,
        "admin_barriers_list": AdminBarriersList,
        "admin_conversations:write": AdminConversationsWrite,
        "admin_conversations_archive": AdminConversationsArchive,
        "admin_conversations_bulkArchive": AdminConversationsBulkarchive,
        "admin_conversations_bulkDelete": AdminConversationsBulkdelete,
        "admin_conversations_bulkMove": AdminConversationsBulkmove,
        "admin_conversations_convertToPrivate": AdminConversationsConverttoprivate,
        "admin_conversations_convertToPublic": AdminConversationsConverttopublic,
        "admin_conversations_create": AdminConversationsCreate,
        "admin_conversations_delete": AdminConversationsDelete,
        "admin_conversations_disconnectShared": AdminConversationsDisconnectshared,
        "admin_conversations_invite": AdminConversationsInvite,
        "admin_conversations_removeCustomRetention": AdminConversationsRemovecustomretention,
        "admin_conversations_rename": AdminConversationsRename,
        "admin_conversations_restrictAccess_addGroup": AdminConversationsRestrictaccessAddgroup,
        "admin_conversations_restrictAccess_removeGroup": AdminConversationsRestrictaccessRemovegroup,
        "admin_conversations_setConversationPrefs": AdminConversationsSetconversationprefs,
        "admin_conversations_setCustomRetention": AdminConversationsSetcustomretention,
        "admin_conversations_setTeams": AdminConversationsSetteams,
        "admin_conversations_unarchive": AdminConversationsUnarchive,
        "admin_conversations:read": AdminConversationsRead,
        "admin_conversations_ekm_listOriginalConnectedChannelInfo": AdminConversationsEkmListoriginalconnectedchannelinfo,
        "admin_conversations_getConversationPrefs": AdminConversationsGetconversationprefs,
        "admin_conversations_getCustomRetention": AdminConversationsGetcustomretention,
        "admin_conversations_getTeams": AdminConversationsGetteams,
        "admin_conversations_lookup": AdminConversationsLookup,
        "admin_conversations_restrictAccess_listGroups": AdminConversationsRestrictaccessListgroups,
        "admin_conversations_search": AdminConversationsSearch,
        "admin_teams:write": AdminTeamsWrite,
        "admin_emoji_add": AdminEmojiAdd,
        "admin_emoji_addAlias": AdminEmojiAddalias,
        "admin_emoji_remove": AdminEmojiRemove,
        "admin_teams_create": AdminTeamsCreate,
        "admin_teams_settings_setDefaultChannels": AdminTeamsSettingsSetdefaultchannels,
        "admin_teams_settings_setDescription": AdminTeamsSettingsSetdescription,
        "admin_teams_settings_setDiscoverability": AdminTeamsSettingsSetdiscoverability,
        "admin_teams_settings_setIcon": AdminTeamsSettingsSeticon,
        "admin_teams_settings_setName": AdminTeamsSettingsSetname,
        "admin_usergroups_addTeams": AdminUsergroupsAddteams,
        "admin_teams:read": AdminTeamsRead,
        "admin_emoji_list": AdminEmojiList,
        "admin_teams_admins_list": AdminTeamsAdminsList,
        "admin_teams_list": AdminTeamsList,
        "admin_teams_owners_list": AdminTeamsOwnersList,
        "admin_teams_settings_info": AdminTeamsSettingsInfo,
        "admin_workflows:read": AdminWorkflowsRead,
        "admin_functions_list": AdminFunctionsList,
        "admin_functions_permissions_lookup": AdminFunctionsPermissionsLookup,
        "admin_workflows_permissions_lookup": AdminWorkflowsPermissionsLookup,
        "admin_workflows_search": AdminWorkflowsSearch,
        "admin_workflows:write": AdminWorkflowsWrite,
        "admin_functions_permissions_set": AdminFunctionsPermissionsSet,
        "admin_workflows_collaborators_add": AdminWorkflowsCollaboratorsAdd,
        "admin_workflows_collaborators_remove": AdminWorkflowsCollaboratorsRemove,
        "admin_workflows_unpublish": AdminWorkflowsUnpublish,
        "admin_invites:write": AdminInvitesWrite,
        "admin_inviteRequests_approve": AdminInviterequestsApprove,
        "admin_inviteRequests_deny": AdminInviterequestsDeny,
        "admin_invites:read": AdminInvitesRead,
        "admin_inviteRequests_approved_list": AdminInviterequestsApprovedList,
        "admin_inviteRequests_denied_list": AdminInviterequestsDeniedList,
        "admin_inviteRequests_list": AdminInviterequestsList,
        "admin_roles:write": AdminRolesWrite,
        "admin_roles_addAssignments": AdminRolesAddassignments,
        "admin_roles_removeAssignments": AdminRolesRemoveassignments,
        "admin_roles:read": AdminRolesRead,
        "admin_roles_listAssignments": AdminRolesListassignments,
        "admin_usergroups:write": AdminUsergroupsWrite,
        "admin_usergroups_addChannels": AdminUsergroupsAddchannels,
        "admin_usergroups_removeChannels": AdminUsergroupsRemovechannels,
        "admin_usergroups:read": AdminUsergroupsRead,
        "admin_usergroups_listChannels": AdminUsergroupsListchannels,
        "hosting:read": HostingRead,
        "apps_activities_list": AppsActivitiesList,
        "connections:write": ConnectionsWrite,
        "apps_connections_open": AppsConnectionsOpen,
        "token": Token,
        "apps_datastore_bulkDelete": AppsDatastoreBulkdelete,
        "apps_datastore_bulkGet": AppsDatastoreBulkget,
        "apps_datastore_bulkPut": AppsDatastoreBulkput,
        "apps_datastore_delete": AppsDatastoreDelete,
        "apps_datastore_get": AppsDatastoreGet,
        "apps_datastore_put": AppsDatastorePut,
        "apps_datastore_query": AppsDatastoreQuery,
        "apps_datastore_update": AppsDatastoreUpdate,
        "datastore:read": DatastoreRead,
        "apps_datastore_count": AppsDatastoreCount,
        "authorizations:read": AuthorizationsRead,
        "apps_event_authorizations_list": AppsEventAuthorizationsList,
        "bot": Bot,
        "auth_revoke": AuthRevoke,
        "auth_test": AuthTest,
        "chat_getPermalink": ChatGetpermalink,
        "chat_scheduledMessages_list": ChatScheduledmessagesList,
        "dialog_open": DialogOpen,
        "functions_completeError": FunctionsCompleteerror,
        "functions_completeSuccess": FunctionsCompletesuccess,
        "rtm_connect": RtmConnect,
        "rtm_start": RtmStart,
        "views_open": ViewsOpen,
        "views_publish": ViewsPublish,
        "views_push": ViewsPush,
        "views_update": ViewsUpdate,
        "bookmarks:write": BookmarksWrite,
        "bookmarks_add": BookmarksAdd,
        "bookmarks_edit": BookmarksEdit,
        "bookmarks_remove": BookmarksRemove,
        "bookmarks:read": BookmarksRead,
        "bookmarks_list": BookmarksList,
        "users:read": UsersRead,
        "bots_info": BotsInfo,
        "users_getPresence": UsersGetpresence,
        "users_info": UsersInfo,
        "users_list": UsersList,
        "calls:write": CallsWrite,
        "calls_add": CallsAdd,
        "calls_end": CallsEnd,
        "calls_participants_add": CallsParticipantsAdd,
        "calls_participants_remove": CallsParticipantsRemove,
        "calls_update": CallsUpdate,
        "calls:read": CallsRead,
        "calls_info": CallsInfo,
        "channels:manage": ChannelsManage,
        "channels_create": ChannelsCreate,
        "channels_mark": ChannelsMark,
        "conversations_archive": ConversationsArchive,
        "conversations_close": ConversationsClose,
        "conversations_create": ConversationsCreate,
        "conversations_kick": ConversationsKick,
        "conversations_leave": ConversationsLeave,
        "conversations_mark": ConversationsMark,
        "conversations_open": ConversationsOpen,
        "conversations_rename": ConversationsRename,
        "conversations_unarchive": ConversationsUnarchive,
        "groups_create": GroupsCreate,
        "groups_mark": GroupsMark,
        "im_mark": ImMark,
        "im_open": ImOpen,
        "mpim_mark": MpimMark,
        "mpim_open": MpimOpen,
        "channels:read": ChannelsRead,
        "channels_info": ChannelsInfo,
        "conversations_info": ConversationsInfo,
        "conversations_list": ConversationsList,
        "conversations_members": ConversationsMembers,
        "groups_info": GroupsInfo,
        "im_list": ImList,
        "mpim_list": MpimList,
        "users_conversations": UsersConversations,
        "channels:write_invites": ChannelsWriteInvites,
        "channels_invite": ChannelsInvite,
        "conversations_invite": ConversationsInvite,
        "groups_invite": GroupsInvite,
        "chat:write": ChatWrite,
        "chat_delete": ChatDelete,
        "chat_deleteScheduledMessage": ChatDeletescheduledmessage,
        "chat_meMessage": ChatMemessage,
        "chat_postEphemeral": ChatPostephemeral,
        "chat_postMessage": ChatPostmessage,
        "chat_scheduleMessage": ChatSchedulemessage,
        "chat_update": ChatUpdate,
        "links:write": LinksWrite,
        "chat_unfurl": ChatUnfurl,
        "conversations_connect:write": ConversationsConnectWrite,
        "conversations_acceptSharedInvite": ConversationsAcceptsharedinvite,
        "conversations_inviteShared": ConversationsInviteshared,
        "conversations_connect:manage": ConversationsConnectManage,
        "conversations_approveSharedInvite": ConversationsApprovesharedinvite,
        "conversations_declineSharedInvite": ConversationsDeclinesharedinvite,
        "conversations_listConnectInvites": ConversationsListconnectinvites,
        "channels:history": ChannelsHistory,
        "conversations_history": ConversationsHistory,
        "conversations_replies": ConversationsReplies,
        "channels:join": ChannelsJoin,
        "conversations_join": ConversationsJoin,
        "channels:write_topic": ChannelsWriteTopic,
        "conversations_setPurpose": ConversationsSetpurpose,
        "conversations_setTopic": ConversationsSettopic,
        "dnd:write": DndWrite,
        "dnd_endDnd": DndEnddnd,
        "dnd_endSnooze": DndEndsnooze,
        "dnd_setSnooze": DndSetsnooze,
        "dnd:read": DndRead,
        "dnd_info": DndInfo,
        "dnd_teamInfo": DndTeaminfo,
        "emoji:read": EmojiRead,
        "emoji_list": EmojiList,
        "files:write": FilesWrite,
        "files_comments_delete": FilesCommentsDelete,
        "files_completeUploadExternal": FilesCompleteuploadexternal,
        "files_delete": FilesDelete,
        "files_getUploadURLExternal": FilesGetuploadurlexternal,
        "files_revokePublicURL": FilesRevokepublicurl,
        "files_sharedPublicURL": FilesSharedpublicurl,
        "files_upload": FilesUpload,
        "files:read": FilesRead,
        "files_info": FilesInfo,
        "files_list": FilesList,
        "remote_files:write": RemoteFilesWrite,
        "files_remote_add": FilesRemoteAdd,
        "files_remote_remove": FilesRemoteRemove,
        "files_remote_update": FilesRemoteUpdate,
        "remote_files:read": RemoteFilesRead,
        "files_remote_info": FilesRemoteInfo,
        "files_remote_list": FilesRemoteList,
        "remote_files:share": RemoteFilesShare,
        "files_remote_share": FilesRemoteShare,
        "app_configurations:write": AppConfigurationsWrite,
        "functions_distributions_permissions_add": FunctionsDistributionsPermissionsAdd,
        "functions_distributions_permissions_remove": FunctionsDistributionsPermissionsRemove,
        "functions_distributions_permissions_set": FunctionsDistributionsPermissionsSet,
        "app_configurations:read": AppConfigurationsRead,
        "functions_distributions_permissions_list": FunctionsDistributionsPermissionsList,
        "conversations": Conversations,
        "groups_open": GroupsOpen,
        "tokens_basic": TokensBasic,
        "migration_exchange": MigrationExchange,
        "email": Email,
        "openid_connect_userInfo": OpenidConnectUserinfo,
        "pins:write": PinsWrite,
        "pins_add": PinsAdd,
        "pins_remove": PinsRemove,
        "pins:read": PinsRead,
        "pins_list": PinsList,
        "reactions:write": ReactionsWrite,
        "reactions_add": ReactionsAdd,
        "reactions_remove": ReactionsRemove,
        "reactions:read": ReactionsRead,
        "reactions_get": ReactionsGet,
        "reactions_list": ReactionsList,
        "reminders:write": RemindersWrite,
        "reminders_add": RemindersAdd,
        "reminders_complete": RemindersComplete,
        "reminders_delete": RemindersDelete,
        "reminders:read": RemindersRead,
        "reminders_info": RemindersInfo,
        "reminders_list": RemindersList,
        "search:read": SearchRead,
        "search_all": SearchAll,
        "search_files": SearchFiles,
        "search_messages": SearchMessages,
        "stars:write": StarsWrite,
        "stars_add": StarsAdd,
        "stars_remove": StarsRemove,
        "stars:read": StarsRead,
        "stars_list": StarsList,
        "admin": Admin,
        "team_accessLogs": TeamAccesslogs,
        "team_billableInfo": TeamBillableinfo,
        "team_integrationLogs": TeamIntegrationlogs,
        "team_billing:read": TeamBillingRead,
        "team_billing_info": TeamBillingInfo,
        "team:read": TeamRead,
        "team_info": TeamInfo,
        "team_preferences:read": TeamPreferencesRead,
        "team_preferences_list": TeamPreferencesList,
        "users_profile:read": UsersProfileRead,
        "team_profile_get": TeamProfileGet,
        "users_profile_get": UsersProfileGet,
        "usergroups:write": UsergroupsWrite,
        "usergroups_create": UsergroupsCreate,
        "usergroups_disable": UsergroupsDisable,
        "usergroups_enable": UsergroupsEnable,
        "usergroups_update": UsergroupsUpdate,
        "usergroups_users_update": UsergroupsUsersUpdate,
        "usergroups:read": UsergroupsRead,
        "usergroups_list": UsergroupsList,
        "usergroups_users_list": UsergroupsUsersList,
        "users_profile:write": UsersProfileWrite,
        "users_deletePhoto": UsersDeletephoto,
        "users_profile_set": UsersProfileSet,
        "users_setPhoto": UsersSetphoto,
        "identity_basic": IdentityBasic,
        "users_identity": UsersIdentity,
        "users:read_email": UsersReadEmail,
        "users_lookupByEmail": UsersLookupbyemail,
        "users:write": UsersWrite,
        "users_setActive": UsersSetactive,
        "users_setPresence": UsersSetpresence,
        "workflow_steps:execute": WorkflowStepsExecute,
        "workflows_stepCompleted": WorkflowsStepcompleted,
        "workflows_stepFailed": WorkflowsStepfailed,
        "workflows_updateStep": WorkflowsUpdatestep,
        "triggers:write": TriggersWrite,
        "workflows_triggers_permissions_add": WorkflowsTriggersPermissionsAdd,
        "workflows_triggers_permissions_remove": WorkflowsTriggersPermissionsRemove,
        "workflows_triggers_permissions_set": WorkflowsTriggersPermissionsSet,
        "triggers:read": TriggersRead,
        "workflows_triggers_permissions_list": WorkflowsTriggersPermissionsList,
    }

    PermissionIDs = map[Permission]int{
        AdminAnalyticsRead: 1,
        AdminAnalyticsGetfile: 2,
        AdminAppActivitiesRead: 3,
        AdminAppsActivitiesList: 4,
        AdminAppsWrite: 5,
        AdminAppsApprove: 6,
        AdminAppsClearresolution: 7,
        AdminAppsConfigSet: 8,
        AdminAppsRequestsCancel: 9,
        AdminAppsRestrict: 10,
        AdminAppsUninstall: 11,
        AdminAppsRead: 12,
        AdminAppsApprovedList: 13,
        AdminAppsConfigLookup: 14,
        AdminAppsRequestsList: 15,
        AdminAppsRestrictedList: 16,
        AdminUsersWrite: 17,
        AdminAuthPolicyAssignentities: 18,
        AdminAuthPolicyRemoveentities: 19,
        AdminUsersAssign: 20,
        AdminUsersInvite: 21,
        AdminUsersRemove: 22,
        AdminUsersSessionClearsettings: 23,
        AdminUsersSessionInvalidate: 24,
        AdminUsersSessionReset: 25,
        AdminUsersSessionResetbulk: 26,
        AdminUsersSessionSetsettings: 27,
        AdminUsersSetadmin: 28,
        AdminUsersSetexpiration: 29,
        AdminUsersSetowner: 30,
        AdminUsersSetregular: 31,
        AdminUsersRead: 32,
        AdminAuthPolicyGetentities: 33,
        AdminUsersList: 34,
        AdminUsersSessionGetsettings: 35,
        AdminUsersSessionList: 36,
        AdminUsersUnsupportedversionsExport: 37,
        AdminBarriersWrite: 38,
        AdminBarriersCreate: 39,
        AdminBarriersDelete: 40,
        AdminBarriersUpdate: 41,
        AdminBarriersRead: 42,
        AdminBarriersList: 43,
        AdminConversationsWrite: 44,
        AdminConversationsArchive: 45,
        AdminConversationsBulkarchive: 46,
        AdminConversationsBulkdelete: 47,
        AdminConversationsBulkmove: 48,
        AdminConversationsConverttoprivate: 49,
        AdminConversationsConverttopublic: 50,
        AdminConversationsCreate: 51,
        AdminConversationsDelete: 52,
        AdminConversationsDisconnectshared: 53,
        AdminConversationsInvite: 54,
        AdminConversationsRemovecustomretention: 55,
        AdminConversationsRename: 56,
        AdminConversationsRestrictaccessAddgroup: 57,
        AdminConversationsRestrictaccessRemovegroup: 58,
        AdminConversationsSetconversationprefs: 59,
        AdminConversationsSetcustomretention: 60,
        AdminConversationsSetteams: 61,
        AdminConversationsUnarchive: 62,
        AdminConversationsRead: 63,
        AdminConversationsEkmListoriginalconnectedchannelinfo: 64,
        AdminConversationsGetconversationprefs: 65,
        AdminConversationsGetcustomretention: 66,
        AdminConversationsGetteams: 67,
        AdminConversationsLookup: 68,
        AdminConversationsRestrictaccessListgroups: 69,
        AdminConversationsSearch: 70,
        AdminTeamsWrite: 71,
        AdminEmojiAdd: 72,
        AdminEmojiAddalias: 73,
        AdminEmojiRemove: 74,
        AdminTeamsCreate: 75,
        AdminTeamsSettingsSetdefaultchannels: 76,
        AdminTeamsSettingsSetdescription: 77,
        AdminTeamsSettingsSetdiscoverability: 78,
        AdminTeamsSettingsSeticon: 79,
        AdminTeamsSettingsSetname: 80,
        AdminUsergroupsAddteams: 81,
        AdminTeamsRead: 82,
        AdminEmojiList: 83,
        AdminTeamsAdminsList: 84,
        AdminTeamsList: 85,
        AdminTeamsOwnersList: 86,
        AdminTeamsSettingsInfo: 87,
        AdminWorkflowsRead: 88,
        AdminFunctionsList: 89,
        AdminFunctionsPermissionsLookup: 90,
        AdminWorkflowsPermissionsLookup: 91,
        AdminWorkflowsSearch: 92,
        AdminWorkflowsWrite: 93,
        AdminFunctionsPermissionsSet: 94,
        AdminWorkflowsCollaboratorsAdd: 95,
        AdminWorkflowsCollaboratorsRemove: 96,
        AdminWorkflowsUnpublish: 97,
        AdminInvitesWrite: 98,
        AdminInviterequestsApprove: 99,
        AdminInviterequestsDeny: 100,
        AdminInvitesRead: 101,
        AdminInviterequestsApprovedList: 102,
        AdminInviterequestsDeniedList: 103,
        AdminInviterequestsList: 104,
        AdminRolesWrite: 105,
        AdminRolesAddassignments: 106,
        AdminRolesRemoveassignments: 107,
        AdminRolesRead: 108,
        AdminRolesListassignments: 109,
        AdminUsergroupsWrite: 110,
        AdminUsergroupsAddchannels: 111,
        AdminUsergroupsRemovechannels: 112,
        AdminUsergroupsRead: 113,
        AdminUsergroupsListchannels: 114,
        HostingRead: 115,
        AppsActivitiesList: 116,
        ConnectionsWrite: 117,
        AppsConnectionsOpen: 118,
        Token: 119,
        AppsDatastoreBulkdelete: 120,
        AppsDatastoreBulkget: 121,
        AppsDatastoreBulkput: 122,
        AppsDatastoreDelete: 123,
        AppsDatastoreGet: 124,
        AppsDatastorePut: 125,
        AppsDatastoreQuery: 126,
        AppsDatastoreUpdate: 127,
        DatastoreRead: 128,
        AppsDatastoreCount: 129,
        AuthorizationsRead: 130,
        AppsEventAuthorizationsList: 131,
        Bot: 132,
        AuthRevoke: 133,
        AuthTest: 134,
        ChatGetpermalink: 135,
        ChatScheduledmessagesList: 136,
        DialogOpen: 137,
        FunctionsCompleteerror: 138,
        FunctionsCompletesuccess: 139,
        RtmConnect: 140,
        RtmStart: 141,
        ViewsOpen: 142,
        ViewsPublish: 143,
        ViewsPush: 144,
        ViewsUpdate: 145,
        BookmarksWrite: 146,
        BookmarksAdd: 147,
        BookmarksEdit: 148,
        BookmarksRemove: 149,
        BookmarksRead: 150,
        BookmarksList: 151,
        UsersRead: 152,
        BotsInfo: 153,
        UsersGetpresence: 154,
        UsersInfo: 155,
        UsersList: 156,
        CallsWrite: 157,
        CallsAdd: 158,
        CallsEnd: 159,
        CallsParticipantsAdd: 160,
        CallsParticipantsRemove: 161,
        CallsUpdate: 162,
        CallsRead: 163,
        CallsInfo: 164,
        ChannelsManage: 165,
        ChannelsCreate: 166,
        ChannelsMark: 167,
        ConversationsArchive: 168,
        ConversationsClose: 169,
        ConversationsCreate: 170,
        ConversationsKick: 171,
        ConversationsLeave: 172,
        ConversationsMark: 173,
        ConversationsOpen: 174,
        ConversationsRename: 175,
        ConversationsUnarchive: 176,
        GroupsCreate: 177,
        GroupsMark: 178,
        ImMark: 179,
        ImOpen: 180,
        MpimMark: 181,
        MpimOpen: 182,
        ChannelsRead: 183,
        ChannelsInfo: 184,
        ConversationsInfo: 185,
        ConversationsList: 186,
        ConversationsMembers: 187,
        GroupsInfo: 188,
        ImList: 189,
        MpimList: 190,
        UsersConversations: 191,
        ChannelsWriteInvites: 192,
        ChannelsInvite: 193,
        ConversationsInvite: 194,
        GroupsInvite: 195,
        ChatWrite: 196,
        ChatDelete: 197,
        ChatDeletescheduledmessage: 198,
        ChatMemessage: 199,
        ChatPostephemeral: 200,
        ChatPostmessage: 201,
        ChatSchedulemessage: 202,
        ChatUpdate: 203,
        LinksWrite: 204,
        ChatUnfurl: 205,
        ConversationsConnectWrite: 206,
        ConversationsAcceptsharedinvite: 207,
        ConversationsInviteshared: 208,
        ConversationsConnectManage: 209,
        ConversationsApprovesharedinvite: 210,
        ConversationsDeclinesharedinvite: 211,
        ConversationsListconnectinvites: 212,
        ChannelsHistory: 213,
        ConversationsHistory: 214,
        ConversationsReplies: 215,
        ChannelsJoin: 216,
        ConversationsJoin: 217,
        ChannelsWriteTopic: 218,
        ConversationsSetpurpose: 219,
        ConversationsSettopic: 220,
        DndWrite: 221,
        DndEnddnd: 222,
        DndEndsnooze: 223,
        DndSetsnooze: 224,
        DndRead: 225,
        DndInfo: 226,
        DndTeaminfo: 227,
        EmojiRead: 228,
        EmojiList: 229,
        FilesWrite: 230,
        FilesCommentsDelete: 231,
        FilesCompleteuploadexternal: 232,
        FilesDelete: 233,
        FilesGetuploadurlexternal: 234,
        FilesRevokepublicurl: 235,
        FilesSharedpublicurl: 236,
        FilesUpload: 237,
        FilesRead: 238,
        FilesInfo: 239,
        FilesList: 240,
        RemoteFilesWrite: 241,
        FilesRemoteAdd: 242,
        FilesRemoteRemove: 243,
        FilesRemoteUpdate: 244,
        RemoteFilesRead: 245,
        FilesRemoteInfo: 246,
        FilesRemoteList: 247,
        RemoteFilesShare: 248,
        FilesRemoteShare: 249,
        AppConfigurationsWrite: 250,
        FunctionsDistributionsPermissionsAdd: 251,
        FunctionsDistributionsPermissionsRemove: 252,
        FunctionsDistributionsPermissionsSet: 253,
        AppConfigurationsRead: 254,
        FunctionsDistributionsPermissionsList: 255,
        Conversations: 256,
        GroupsOpen: 257,
        TokensBasic: 258,
        MigrationExchange: 259,
        Email: 260,
        OpenidConnectUserinfo: 261,
        PinsWrite: 262,
        PinsAdd: 263,
        PinsRemove: 264,
        PinsRead: 265,
        PinsList: 266,
        ReactionsWrite: 267,
        ReactionsAdd: 268,
        ReactionsRemove: 269,
        ReactionsRead: 270,
        ReactionsGet: 271,
        ReactionsList: 272,
        RemindersWrite: 273,
        RemindersAdd: 274,
        RemindersComplete: 275,
        RemindersDelete: 276,
        RemindersRead: 277,
        RemindersInfo: 278,
        RemindersList: 279,
        SearchRead: 280,
        SearchAll: 281,
        SearchFiles: 282,
        SearchMessages: 283,
        StarsWrite: 284,
        StarsAdd: 285,
        StarsRemove: 286,
        StarsRead: 287,
        StarsList: 288,
        Admin: 289,
        TeamAccesslogs: 290,
        TeamBillableinfo: 291,
        TeamIntegrationlogs: 292,
        TeamBillingRead: 293,
        TeamBillingInfo: 294,
        TeamRead: 295,
        TeamInfo: 296,
        TeamPreferencesRead: 297,
        TeamPreferencesList: 298,
        UsersProfileRead: 299,
        TeamProfileGet: 300,
        UsersProfileGet: 301,
        UsergroupsWrite: 302,
        UsergroupsCreate: 303,
        UsergroupsDisable: 304,
        UsergroupsEnable: 305,
        UsergroupsUpdate: 306,
        UsergroupsUsersUpdate: 307,
        UsergroupsRead: 308,
        UsergroupsList: 309,
        UsergroupsUsersList: 310,
        UsersProfileWrite: 311,
        UsersDeletephoto: 312,
        UsersProfileSet: 313,
        UsersSetphoto: 314,
        IdentityBasic: 315,
        UsersIdentity: 316,
        UsersReadEmail: 317,
        UsersLookupbyemail: 318,
        UsersWrite: 319,
        UsersSetactive: 320,
        UsersSetpresence: 321,
        WorkflowStepsExecute: 322,
        WorkflowsStepcompleted: 323,
        WorkflowsStepfailed: 324,
        WorkflowsUpdatestep: 325,
        TriggersWrite: 326,
        WorkflowsTriggersPermissionsAdd: 327,
        WorkflowsTriggersPermissionsRemove: 328,
        WorkflowsTriggersPermissionsSet: 329,
        TriggersRead: 330,
        WorkflowsTriggersPermissionsList: 331,
    }

    IdToPermission = map[int]Permission{
        1: AdminAnalyticsRead,
        2: AdminAnalyticsGetfile,
        3: AdminAppActivitiesRead,
        4: AdminAppsActivitiesList,
        5: AdminAppsWrite,
        6: AdminAppsApprove,
        7: AdminAppsClearresolution,
        8: AdminAppsConfigSet,
        9: AdminAppsRequestsCancel,
        10: AdminAppsRestrict,
        11: AdminAppsUninstall,
        12: AdminAppsRead,
        13: AdminAppsApprovedList,
        14: AdminAppsConfigLookup,
        15: AdminAppsRequestsList,
        16: AdminAppsRestrictedList,
        17: AdminUsersWrite,
        18: AdminAuthPolicyAssignentities,
        19: AdminAuthPolicyRemoveentities,
        20: AdminUsersAssign,
        21: AdminUsersInvite,
        22: AdminUsersRemove,
        23: AdminUsersSessionClearsettings,
        24: AdminUsersSessionInvalidate,
        25: AdminUsersSessionReset,
        26: AdminUsersSessionResetbulk,
        27: AdminUsersSessionSetsettings,
        28: AdminUsersSetadmin,
        29: AdminUsersSetexpiration,
        30: AdminUsersSetowner,
        31: AdminUsersSetregular,
        32: AdminUsersRead,
        33: AdminAuthPolicyGetentities,
        34: AdminUsersList,
        35: AdminUsersSessionGetsettings,
        36: AdminUsersSessionList,
        37: AdminUsersUnsupportedversionsExport,
        38: AdminBarriersWrite,
        39: AdminBarriersCreate,
        40: AdminBarriersDelete,
        41: AdminBarriersUpdate,
        42: AdminBarriersRead,
        43: AdminBarriersList,
        44: AdminConversationsWrite,
        45: AdminConversationsArchive,
        46: AdminConversationsBulkarchive,
        47: AdminConversationsBulkdelete,
        48: AdminConversationsBulkmove,
        49: AdminConversationsConverttoprivate,
        50: AdminConversationsConverttopublic,
        51: AdminConversationsCreate,
        52: AdminConversationsDelete,
        53: AdminConversationsDisconnectshared,
        54: AdminConversationsInvite,
        55: AdminConversationsRemovecustomretention,
        56: AdminConversationsRename,
        57: AdminConversationsRestrictaccessAddgroup,
        58: AdminConversationsRestrictaccessRemovegroup,
        59: AdminConversationsSetconversationprefs,
        60: AdminConversationsSetcustomretention,
        61: AdminConversationsSetteams,
        62: AdminConversationsUnarchive,
        63: AdminConversationsRead,
        64: AdminConversationsEkmListoriginalconnectedchannelinfo,
        65: AdminConversationsGetconversationprefs,
        66: AdminConversationsGetcustomretention,
        67: AdminConversationsGetteams,
        68: AdminConversationsLookup,
        69: AdminConversationsRestrictaccessListgroups,
        70: AdminConversationsSearch,
        71: AdminTeamsWrite,
        72: AdminEmojiAdd,
        73: AdminEmojiAddalias,
        74: AdminEmojiRemove,
        75: AdminTeamsCreate,
        76: AdminTeamsSettingsSetdefaultchannels,
        77: AdminTeamsSettingsSetdescription,
        78: AdminTeamsSettingsSetdiscoverability,
        79: AdminTeamsSettingsSeticon,
        80: AdminTeamsSettingsSetname,
        81: AdminUsergroupsAddteams,
        82: AdminTeamsRead,
        83: AdminEmojiList,
        84: AdminTeamsAdminsList,
        85: AdminTeamsList,
        86: AdminTeamsOwnersList,
        87: AdminTeamsSettingsInfo,
        88: AdminWorkflowsRead,
        89: AdminFunctionsList,
        90: AdminFunctionsPermissionsLookup,
        91: AdminWorkflowsPermissionsLookup,
        92: AdminWorkflowsSearch,
        93: AdminWorkflowsWrite,
        94: AdminFunctionsPermissionsSet,
        95: AdminWorkflowsCollaboratorsAdd,
        96: AdminWorkflowsCollaboratorsRemove,
        97: AdminWorkflowsUnpublish,
        98: AdminInvitesWrite,
        99: AdminInviterequestsApprove,
        100: AdminInviterequestsDeny,
        101: AdminInvitesRead,
        102: AdminInviterequestsApprovedList,
        103: AdminInviterequestsDeniedList,
        104: AdminInviterequestsList,
        105: AdminRolesWrite,
        106: AdminRolesAddassignments,
        107: AdminRolesRemoveassignments,
        108: AdminRolesRead,
        109: AdminRolesListassignments,
        110: AdminUsergroupsWrite,
        111: AdminUsergroupsAddchannels,
        112: AdminUsergroupsRemovechannels,
        113: AdminUsergroupsRead,
        114: AdminUsergroupsListchannels,
        115: HostingRead,
        116: AppsActivitiesList,
        117: ConnectionsWrite,
        118: AppsConnectionsOpen,
        119: Token,
        120: AppsDatastoreBulkdelete,
        121: AppsDatastoreBulkget,
        122: AppsDatastoreBulkput,
        123: AppsDatastoreDelete,
        124: AppsDatastoreGet,
        125: AppsDatastorePut,
        126: AppsDatastoreQuery,
        127: AppsDatastoreUpdate,
        128: DatastoreRead,
        129: AppsDatastoreCount,
        130: AuthorizationsRead,
        131: AppsEventAuthorizationsList,
        132: Bot,
        133: AuthRevoke,
        134: AuthTest,
        135: ChatGetpermalink,
        136: ChatScheduledmessagesList,
        137: DialogOpen,
        138: FunctionsCompleteerror,
        139: FunctionsCompletesuccess,
        140: RtmConnect,
        141: RtmStart,
        142: ViewsOpen,
        143: ViewsPublish,
        144: ViewsPush,
        145: ViewsUpdate,
        146: BookmarksWrite,
        147: BookmarksAdd,
        148: BookmarksEdit,
        149: BookmarksRemove,
        150: BookmarksRead,
        151: BookmarksList,
        152: UsersRead,
        153: BotsInfo,
        154: UsersGetpresence,
        155: UsersInfo,
        156: UsersList,
        157: CallsWrite,
        158: CallsAdd,
        159: CallsEnd,
        160: CallsParticipantsAdd,
        161: CallsParticipantsRemove,
        162: CallsUpdate,
        163: CallsRead,
        164: CallsInfo,
        165: ChannelsManage,
        166: ChannelsCreate,
        167: ChannelsMark,
        168: ConversationsArchive,
        169: ConversationsClose,
        170: ConversationsCreate,
        171: ConversationsKick,
        172: ConversationsLeave,
        173: ConversationsMark,
        174: ConversationsOpen,
        175: ConversationsRename,
        176: ConversationsUnarchive,
        177: GroupsCreate,
        178: GroupsMark,
        179: ImMark,
        180: ImOpen,
        181: MpimMark,
        182: MpimOpen,
        183: ChannelsRead,
        184: ChannelsInfo,
        185: ConversationsInfo,
        186: ConversationsList,
        187: ConversationsMembers,
        188: GroupsInfo,
        189: ImList,
        190: MpimList,
        191: UsersConversations,
        192: ChannelsWriteInvites,
        193: ChannelsInvite,
        194: ConversationsInvite,
        195: GroupsInvite,
        196: ChatWrite,
        197: ChatDelete,
        198: ChatDeletescheduledmessage,
        199: ChatMemessage,
        200: ChatPostephemeral,
        201: ChatPostmessage,
        202: ChatSchedulemessage,
        203: ChatUpdate,
        204: LinksWrite,
        205: ChatUnfurl,
        206: ConversationsConnectWrite,
        207: ConversationsAcceptsharedinvite,
        208: ConversationsInviteshared,
        209: ConversationsConnectManage,
        210: ConversationsApprovesharedinvite,
        211: ConversationsDeclinesharedinvite,
        212: ConversationsListconnectinvites,
        213: ChannelsHistory,
        214: ConversationsHistory,
        215: ConversationsReplies,
        216: ChannelsJoin,
        217: ConversationsJoin,
        218: ChannelsWriteTopic,
        219: ConversationsSetpurpose,
        220: ConversationsSettopic,
        221: DndWrite,
        222: DndEnddnd,
        223: DndEndsnooze,
        224: DndSetsnooze,
        225: DndRead,
        226: DndInfo,
        227: DndTeaminfo,
        228: EmojiRead,
        229: EmojiList,
        230: FilesWrite,
        231: FilesCommentsDelete,
        232: FilesCompleteuploadexternal,
        233: FilesDelete,
        234: FilesGetuploadurlexternal,
        235: FilesRevokepublicurl,
        236: FilesSharedpublicurl,
        237: FilesUpload,
        238: FilesRead,
        239: FilesInfo,
        240: FilesList,
        241: RemoteFilesWrite,
        242: FilesRemoteAdd,
        243: FilesRemoteRemove,
        244: FilesRemoteUpdate,
        245: RemoteFilesRead,
        246: FilesRemoteInfo,
        247: FilesRemoteList,
        248: RemoteFilesShare,
        249: FilesRemoteShare,
        250: AppConfigurationsWrite,
        251: FunctionsDistributionsPermissionsAdd,
        252: FunctionsDistributionsPermissionsRemove,
        253: FunctionsDistributionsPermissionsSet,
        254: AppConfigurationsRead,
        255: FunctionsDistributionsPermissionsList,
        256: Conversations,
        257: GroupsOpen,
        258: TokensBasic,
        259: MigrationExchange,
        260: Email,
        261: OpenidConnectUserinfo,
        262: PinsWrite,
        263: PinsAdd,
        264: PinsRemove,
        265: PinsRead,
        266: PinsList,
        267: ReactionsWrite,
        268: ReactionsAdd,
        269: ReactionsRemove,
        270: ReactionsRead,
        271: ReactionsGet,
        272: ReactionsList,
        273: RemindersWrite,
        274: RemindersAdd,
        275: RemindersComplete,
        276: RemindersDelete,
        277: RemindersRead,
        278: RemindersInfo,
        279: RemindersList,
        280: SearchRead,
        281: SearchAll,
        282: SearchFiles,
        283: SearchMessages,
        284: StarsWrite,
        285: StarsAdd,
        286: StarsRemove,
        287: StarsRead,
        288: StarsList,
        289: Admin,
        290: TeamAccesslogs,
        291: TeamBillableinfo,
        292: TeamIntegrationlogs,
        293: TeamBillingRead,
        294: TeamBillingInfo,
        295: TeamRead,
        296: TeamInfo,
        297: TeamPreferencesRead,
        298: TeamPreferencesList,
        299: UsersProfileRead,
        300: TeamProfileGet,
        301: UsersProfileGet,
        302: UsergroupsWrite,
        303: UsergroupsCreate,
        304: UsergroupsDisable,
        305: UsergroupsEnable,
        306: UsergroupsUpdate,
        307: UsergroupsUsersUpdate,
        308: UsergroupsRead,
        309: UsergroupsList,
        310: UsergroupsUsersList,
        311: UsersProfileWrite,
        312: UsersDeletephoto,
        313: UsersProfileSet,
        314: UsersSetphoto,
        315: IdentityBasic,
        316: UsersIdentity,
        317: UsersReadEmail,
        318: UsersLookupbyemail,
        319: UsersWrite,
        320: UsersSetactive,
        321: UsersSetpresence,
        322: WorkflowStepsExecute,
        323: WorkflowsStepcompleted,
        324: WorkflowsStepfailed,
        325: WorkflowsUpdatestep,
        326: TriggersWrite,
        327: WorkflowsTriggersPermissionsAdd,
        328: WorkflowsTriggersPermissionsRemove,
        329: WorkflowsTriggersPermissionsSet,
        330: TriggersRead,
        331: WorkflowsTriggersPermissionsList,
    }
)

// ToString converts a Permission enum to its string representation
func (p Permission) ToString() (string, error) {
    if str, ok := PermissionStrings[p]; ok {
        return str, nil
    }
    return "", errors.New("invalid permission")
}

// ToID converts a Permission enum to its ID
func (p Permission) ToID() (int, error) {
    if id, ok := PermissionIDs[p]; ok {
        return id, nil
    }
    return 0, errors.New("invalid permission")
}

// PermissionFromString converts a string representation to its Permission enum
func PermissionFromString(s string) (Permission, error) {
    if p, ok := StringToPermission[s]; ok {
        return p, nil
    }
    return 0, errors.New("invalid permission string")
}

// PermissionFromID converts an ID to its Permission enum
func PermissionFromID(id int) (Permission, error) {
    if p, ok := IdToPermission[id]; ok {
        return p, nil
    }
    return 0, errors.New("invalid permission ID")
}
