// Code generated by go generate; DO NOT EDIT.
package gitlab

import "errors"

type Permission int

const (
    Invalid Permission = iota
    Api Permission = iota
    ReadUser Permission = iota
    ReadApi Permission = iota
    ReadRepository Permission = iota
    WriteRepository Permission = iota
    ReadRegistry Permission = iota
    WriteRegistry Permission = iota
    Sudo Permission = iota
    AdminMode Permission = iota
    CreateRunner Permission = iota
    ManageRunner Permission = iota
    AiFeatures Permission = iota
    K8sProxy Permission = iota
    ReadServicePing Permission = iota
)

var (
    PermissionStrings = map[Permission]string{
        Api: "api",
        ReadUser: "read_user",
        ReadApi: "read_api",
        ReadRepository: "read_repository",
        WriteRepository: "write_repository",
        ReadRegistry: "read_registry",
        WriteRegistry: "write_registry",
        Sudo: "sudo",
        AdminMode: "admin_mode",
        CreateRunner: "create_runner",
        ManageRunner: "manage_runner",
        AiFeatures: "ai_features",
        K8sProxy: "k8s_proxy",
        ReadServicePing: "read_service_ping",
    }

    StringToPermission = map[string]Permission{
        "api": Api,
        "read_user": ReadUser,
        "read_api": ReadApi,
        "read_repository": ReadRepository,
        "write_repository": WriteRepository,
        "read_registry": ReadRegistry,
        "write_registry": WriteRegistry,
        "sudo": Sudo,
        "admin_mode": AdminMode,
        "create_runner": CreateRunner,
        "manage_runner": ManageRunner,
        "ai_features": AiFeatures,
        "k8s_proxy": K8sProxy,
        "read_service_ping": ReadServicePing,
    }

    PermissionIDs = map[Permission]int{
        Api: 1,
        ReadUser: 2,
        ReadApi: 3,
        ReadRepository: 4,
        WriteRepository: 5,
        ReadRegistry: 6,
        WriteRegistry: 7,
        Sudo: 8,
        AdminMode: 9,
        CreateRunner: 10,
        ManageRunner: 11,
        AiFeatures: 12,
        K8sProxy: 13,
        ReadServicePing: 14,
    }

    IdToPermission = map[int]Permission{
        1: Api,
        2: ReadUser,
        3: ReadApi,
        4: ReadRepository,
        5: WriteRepository,
        6: ReadRegistry,
        7: WriteRegistry,
        8: Sudo,
        9: AdminMode,
        10: CreateRunner,
        11: ManageRunner,
        12: AiFeatures,
        13: K8sProxy,
        14: ReadServicePing,
    }

    permissionDescriptions = map[string]string{
        "api":               "Grants complete read/write access to the API, including all groups and projects, the container registry, the dependency proxy, and the package registry. Also grants complete read/write access to the registry and repository using Git over HTTP.",
        "read_user":         "Grants read-only access to the authenticated user’s profile through the /user API endpoint, which includes username, public email, and full name. Also grants access to read-only API endpoints under /users.",
        "read_api":          "Grants read access to the API, including all groups and projects, the container registry, and the package registry.",
        "read_repository":   "Grants read-only access to repositories on private projects using Git-over-HTTP or the Repository Files API.",
        "write_repository":  "Grants read-write access to repositories on private projects using Git-over-HTTP (not using the API).",
        "read_registry":     "Grants read-only (pull) access to container registry images if a project is private and authorization is required. Available only when the container registry is enabled.",
        "write_registry":    "Grants read-write (push) access to container registry images if a project is private and authorization is required. Available only when the container registry is enabled.",
        "sudo":              "Grants permission to perform API actions as any user in the system, when authenticated as an administrator.",
        "admin_mode":        "Grants permission to perform API actions as an administrator, when Admin Mode is enabled. (Introduced in GitLab 15.8.)",
        "create_runner":     "Grants permission to create runners.",
        "manage_runner":     "Grants permission to manage runners.",
        "ai_features":       "Grants permission to perform API actions for GitLab Duo. This scope is designed to work with the GitLab Duo Plugin for JetBrains. For all other extensions, see scope requirements.",
        "k8s_proxy":         "Grants permission to perform Kubernetes API calls using the agent for Kubernetes.",
        "read_service_ping": "Grant access to download Service Ping payload through the API when authenticated as an admin use. (Introduced in GitLab 16.8.",
    }

    access_level_map = map[int]string{
        0:  "No access",
        5:  "Minimal access",
        10: "Guest",
        20: "Reporter",
        30: "Developer",
        40: "Maintainer",
        50: "Owner",
    }
)

// ToString converts a Permission enum to its string representation
func (p Permission) ToString() (string, error) {
    if str, ok := PermissionStrings[p]; ok {
        return str, nil
    }
    return "", errors.New("invalid permission")
}

// ToID converts a Permission enum to its ID
func (p Permission) ToID() (int, error) {
    if id, ok := PermissionIDs[p]; ok {
        return id, nil
    }
    return 0, errors.New("invalid permission")
}

// PermissionFromString converts a string representation to its Permission enum
func PermissionFromString(s string) (Permission, error) {
    if p, ok := StringToPermission[s]; ok {
        return p, nil
    }
    return 0, errors.New("invalid permission string")
}

// PermissionFromID converts an ID to its Permission enum
func PermissionFromID(id int) (Permission, error) {
    if p, ok := IdToPermission[id]; ok {
        return p, nil
    }
    return 0, errors.New("invalid permission ID")
}
